# Title:Healthcare Operations, Clinical Outcomes & Financial Performance Analytics

│
├── 1. Project Introduction
│
├── 2. Import Libraries
│
├── 3. Load Healthcare Data
│
├── 4. Dataset Overview
│
├── 5. Data Cleaning
│
├── 6. Exploratory Data Analysis
│
├── 7. Statistical Analysis
│
├── 8. Healthcare Visualizations
│   ├── Admissions by Department
│   ├── Gender Distribution
│   ├── Age Distribution
│   ├── Insurance Distribution
│   ├── Smoking Status
│   ├── Payment Distribution
│   ├── Laboratory Results
│   ├── Correlation Heatmap
│   ├── Admissions by Gender
│   ├── Admissions by Insurance
│   └── Payment by Method
│
├── 9. Key Healthcare Insights
│
└── 10. Conclusion

# Project Overview

This project analyses hospital patient, clinical, operational, insurance, and financial data to uncover insights into healthcare demand, resource utilisation, and financial performance. 

The analysis connects patient care activities with operational efficiency and insurance reimbursement outcomes to support data-driven decision-making

# Project Objective

To develop an integrated healthcare analytics solution that combines patient, operational, clinical, insurance, and financial data to improve decision-making, optimise hospital performance, enhance patient care outcomes, and support sustainable financial growth.

This version reads like a real healthcare analytics case study and would fit well in a Power BI, SQL, Python, or data analytics portfolio.

# ==============================================
# IMPORT LIBRARIES
# =============================================

In [1]:
# Data manipulation and analysis
import pandas as pd
import numpy as np

# Data visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Statistical analysis
import scipy.stats as stats

# File and path management
from pathlib import Path

# Date and time
from datetime import datetime

# Warning management
import warnings

# Ignore unnecessary warnings
warnings.filterwarnings("ignore")

# Set visualization style
sns.set_theme(style="whitegrid")

print("All libraries imported successfully.")

All libraries imported successfully.

# 1. Load Healthcare Dataset

This section loads all healthcare CSV files using the modular
`data_loader.py` module and stores them in the `data` dictionary.

In [2]:
from data_loader import load_all_data

data = load_all_data()

for name, df in data.items():
    print(f"{name}: {df.shape}")

patients: (2515, 11)
admissions: (6500, 12)
dataset_summary: (14, 3)
departments: (12, 3)
diagnoses: (35, 4)
diagnosis_records: (5250, 6)
doctors: (80, 6)
insurance_claims: (6200, 9)
lab_results: (18000, 7)
lab_tests: (26, 5)
medication_records: (11000, 8)
medications: (45, 5)
payments: (5800, 7)
procedure_records: (8500, 6)
procedures: (40, 4)

# Create DataFrame References

In [3]:
df_patients = data["patients"]
df_admissions = data["admissions"]
df_departments = data["departments"]
df_diagnoses = data["diagnoses"]
df_diagnosis_records = data["diagnosis_records"]
df_doctors = data["doctors"]
df_insurance_claims = data["insurance_claims"]
df_lab_results = data["lab_results"]
df_lab_tests = data["lab_tests"]
df_medication_records = data["medication_records"]
df_medications = data["medications"]
df_payments = data["payments"]
df_procedure_records = data["procedure_records"]
df_procedures = data["procedures"]
df_procedures

    Procedure_ID           Procedure_Name Procedure_Category  Base_Cost
0           5001               Blood Test           Surgical     397.76
1           5002                    X-Ray           Surgical     582.58
2           5003                  CT Scan         Preventive    1074.45
3           5004                      MRI         Preventive     122.40
4           5005               Ultrasound         Preventive     557.12
5           5006                      ECG         Preventive    1191.81
6           5007           Echocardiogram         Preventive     325.54
7           5008              Colonoscopy           Surgical     204.13
8           5009                Endoscopy         Diagnostic     469.35
9           5010             Appendectomy         Diagnostic     518.77
10          5011          Hip Replacement         Diagnostic     263.24
11          5012         Knee Replacement           Surgical    2912.97
12          5013                     CABG        Therapeutic     371.31
13          5014              Angioplasty           Surgical     216.39
14          5015                   Biopsy         Diagnostic     505.28
15          5016             Chemotherapy         Diagnostic    1125.84
16          5017        Radiation Therapy         Preventive     552.21
17          5018                 Dialysis         Preventive     803.10
18          5019         Physical Therapy         Preventive     271.18
19          5020               Wound Care           Surgical    1790.32
20          5021              Vaccination        Therapeutic     853.52
21          5022                C-Section        Therapeutic    1259.11
22          5023          Normal Delivery         Preventive     729.33
23          5024     Laparoscopic Surgery        Therapeutic    1053.54
24          5025          Fracture Repair         Diagnostic     270.85
25          5026         Cataract Surgery         Diagnostic     367.55
26          5027         Dental Procedure         Preventive    1599.08
27          5028           Skin Procedure         Preventive    1896.55
28          5029  Pulmonary Function Test         Preventive     217.53
29          5030                    Other        Therapeutic     665.00
30          5031              Procedure 0           Surgical     385.77
31          5032              Procedure 1         Preventive     311.80
32          5033              Procedure 2        Therapeutic     683.94
33          5034              Procedure 3         Preventive    1356.65
34          5035              Procedure 4           Surgical     781.59
35          5036              Procedure 5         Preventive     421.74
36          5037              Procedure 6         Diagnostic     822.12
37          5038              Procedure 7         Preventive     408.31
38          5039              Procedure 8         Diagnostic     757.25
39          5040              Procedure 9         Diagnostic    1664.32

# 2. Clean Healthcare Dataset

# 5. Data Cleaning

The healthcare datasets are cleaned before performing exploratory data analysis, statistical analysis, and visualization.

The cleaning process includes:

- Removing duplicate rows

- Standardizing column names

- Preserving the original data by working with copies

- Applying the same basic cleaning process to all healthcare tables

In [4]:
from data_cleaning import clean_all_data

cleaned_data = clean_all_data(data)

for name, df in cleaned_data.items():
    print(f"{name}: {df.shape}")
data = cleaned_data

#print(data)

for name, df in cleaned_data.items():
    print(f"\n{name}")
    print(df.columns.tolist())

patients: (2500, 11)
admissions: (6500, 12)
dataset_summary: (14, 3)
departments: (12, 3)
diagnoses: (35, 4)
diagnosis_records: (5250, 6)
doctors: (80, 6)
insurance_claims: (6200, 9)
lab_results: (18000, 7)
lab_tests: (26, 5)
medication_records: (11000, 8)
medications: (45, 5)
payments: (5800, 7)
procedure_records: (8500, 6)
procedures: (40, 4)

patients
['patient_id', 'first_name', 'last_name', 'gender', 'date_of_birth', 'city', 'state', 'insurance_type', 'smoking_status', 'blood_type', 'registration_date']

admissions
['admission_id', 'patient_id', 'doctor_id', 'department_id', 'admission_date', 'discharge_date', 'admission_type', 'discharge_status', 'length_of_stay', 'room_type', 'readmission_30_days', 'patient_satisfaction']

dataset_summary
['csv_file', 'rows', 'columns']

departments
['department_id', 'department_name', 'specialty_group']

diagnoses
['diagnosis_id', 'diagnosis_name', 'icd10_code', 'diagnosis_category']

diagnosis_records
['diagnosis_record_id', 'admission_id', 'diagnosis_id', 'primary_diagnosis', 'diagnosis_date', 'severity']

doctors
['doctor_id', 'doctor_name', 'department_id', 'specialty', 'years_experience', 'employment_type']

insurance_claims
['claim_id', 'admission_id', 'patient_id', 'claim_date', 'insurance_type', 'billed_amount', 'approved_amount', 'denied_amount', 'claim_status']

lab_results
['lab_result_id', 'admission_id', 'lab_test_id', 'test_date', 'result_value', 'result_unit', 'abnormal_flag']

lab_tests
['lab_test_id', 'lab_test_name', 'category', 'reference_low', 'reference_high']

medication_records
['medication_record_id', 'admission_id', 'medication_id', 'start_date', 'dose', 'dose_unit', 'frequency', 'route']

medications
['medication_id', 'medication_name', 'medication_class', 'generic_name', 'unit_cost']

payments
['payment_id', 'claim_id', 'patient_id', 'payment_date', 'payment_method', 'payment_amount', 'payment_status']

procedure_records
['procedure_record_id', 'admission_id', 'procedure_id', 'procedure_date', 'outcome', 'actual_cost']

procedures
['procedure_id', 'procedure_name', 'procedure_category', 'base_cost']

# Healthcare Exploratory Data Analysis (EDA)

This section imports the healthcare EDA module, reloads the module, and executes all EDA functions on the healthcare dataset.

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import importlib
import healthcare_eda

importlib.reload(healthcare_eda)

print("healthcare_eda module loaded successfully.")

print("Libraries imported successfully.")

healthcare_eda module loaded successfully.
Libraries imported successfully.

In [7]:
for table_name, df in data.items():

    print("=" * 70)
    print(table_name.upper())

    if isinstance(df, pd.DataFrame):

        print("Type:", type(df))
        print("Shape:", df.shape)
        print("Columns:")
        print(df.columns.tolist())

    else:

        print("Type:", type(df))

    print()

======================================================================
PATIENTS
Type: <class 'pandas.DataFrame'>
Shape: (2500, 11)
Columns:
['patient_id', 'first_name', 'last_name', 'gender', 'date_of_birth', 'city', 'state', 'insurance_type', 'smoking_status', 'blood_type', 'registration_date']

======================================================================
ADMISSIONS
Type: <class 'pandas.DataFrame'>
Shape: (6500, 12)
Columns:
['admission_id', 'patient_id', 'doctor_id', 'department_id', 'admission_date', 'discharge_date', 'admission_type', 'discharge_status', 'length_of_stay', 'room_type', 'readmission_30_days', 'patient_satisfaction']

======================================================================
DATASET_SUMMARY
Type: <class 'pandas.DataFrame'>
Shape: (14, 3)
Columns:
['csv_file', 'rows', 'columns']

======================================================================
DEPARTMENTS
Type: <class 'pandas.DataFrame'>
Shape: (12, 3)
Columns:
['department_id', 'department_name', 'specialty_group']

======================================================================
DIAGNOSES
Type: <class 'pandas.DataFrame'>
Shape: (35, 4)
Columns:
['diagnosis_id', 'diagnosis_name', 'icd10_code', 'diagnosis_category']

======================================================================
DIAGNOSIS_RECORDS
Type: <class 'pandas.DataFrame'>
Shape: (5250, 6)
Columns:
['diagnosis_record_id', 'admission_id', 'diagnosis_id', 'primary_diagnosis', 'diagnosis_date', 'severity']

======================================================================
DOCTORS
Type: <class 'pandas.DataFrame'>
Shape: (80, 6)
Columns:
['doctor_id', 'doctor_name', 'department_id', 'specialty', 'years_experience', 'employment_type']

======================================================================
INSURANCE_CLAIMS
Type: <class 'pandas.DataFrame'>
Shape: (6200, 9)
Columns:
['claim_id', 'admission_id', 'patient_id', 'claim_date', 'insurance_type', 'billed_amount', 'approved_amount', 'denied_amount', 'claim_status']

======================================================================
LAB_RESULTS
Type: <class 'pandas.DataFrame'>
Shape: (18000, 7)
Columns:
['lab_result_id', 'admission_id', 'lab_test_id', 'test_date', 'result_value', 'result_unit', 'abnormal_flag']

======================================================================
LAB_TESTS
Type: <class 'pandas.DataFrame'>
Shape: (26, 5)
Columns:
['lab_test_id', 'lab_test_name', 'category', 'reference_low', 'reference_high']

======================================================================
MEDICATION_RECORDS
Type: <class 'pandas.DataFrame'>
Shape: (11000, 8)
Columns:
['medication_record_id', 'admission_id', 'medication_id', 'start_date', 'dose', 'dose_unit', 'frequency', 'route']

======================================================================
MEDICATIONS
Type: <class 'pandas.DataFrame'>
Shape: (45, 5)
Columns:
['medication_id', 'medication_name', 'medication_class', 'generic_name', 'unit_cost']

======================================================================
PAYMENTS
Type: <class 'pandas.DataFrame'>
Shape: (5800, 7)
Columns:
['payment_id', 'claim_id', 'patient_id', 'payment_date', 'payment_method', 'payment_amount', 'payment_status']

======================================================================
PROCEDURE_RECORDS
Type: <class 'pandas.DataFrame'>
Shape: (8500, 6)
Columns:
['procedure_record_id', 'admission_id', 'procedure_id', 'procedure_date', 'outcome', 'actual_cost']

======================================================================
PROCEDURES
Type: <class 'pandas.DataFrame'>
Shape: (40, 4)
Columns:
['procedure_id', 'procedure_name', 'procedure_category', 'base_cost']

In [15]:
# Run Exploratory Data Analysis across all healthcare datasets
eda_results = healthcare_eda.healthcare_eda(cleaned_data)

# Confirm successful execution
print("Healthcare EDA completed successfully.")
print("Number of EDA sections:", len(eda_results))

Healthcare EDA completed successfully.
Number of EDA sections: 14

In [14]:
for section, result in eda_results.items():

    print("=" * 70)
    print(section.upper())
    print("=" * 70)

    if isinstance(result, dict):

        if "error" in result:

            print("ERROR:", result["error"])

        else:

            print("EDA completed successfully.")
            print("Number of metrics:", len(result))

    else:

        print("Unexpected result type:", type(result))

    print()

======================================================================
ADMISSIONS
======================================================================
EDA completed successfully.
Number of metrics: 15

======================================================================
DEPARTMENTS
======================================================================
EDA completed successfully.
Number of metrics: 3

======================================================================
DOCTORS
======================================================================
EDA completed successfully.
Number of metrics: 3

======================================================================
PATIENTS
======================================================================
EDA completed successfully.
Number of metrics: 12

======================================================================
DIAGNOSES
======================================================================
EDA completed successfully.
Number of metrics: 3

======================================================================
DIAGNOSIS_RECORDS
======================================================================
EDA completed successfully.
Number of metrics: 4

======================================================================
INSURANCE_CLAIMS
======================================================================
EDA completed successfully.
Number of metrics: 14

======================================================================
PAYMENTS
======================================================================
EDA completed successfully.
Number of metrics: 9

======================================================================
LAB_TESTS
======================================================================
EDA completed successfully.
Number of metrics: 3

======================================================================
LAB_RESULTS
======================================================================
EDA completed successfully.
Number of metrics: 8

======================================================================
MEDICATIONS
======================================================================
EDA completed successfully.
Number of metrics: 3

======================================================================
MEDICATION_RECORDS
======================================================================
EDA completed successfully.
Number of metrics: 6

======================================================================
PROCEDURES
======================================================================
EDA completed successfully.
Number of metrics: 3

======================================================================
PROCEDURE_RECORDS
======================================================================
EDA completed successfully.
Number of metrics: 8

In [16]:
# ============================================================
# RUN HEALTHCARE EDA
# ============================================================

from healthcare_eda import healthcare_eda

# Run EDA on your loaded data
healthcare_eda_results = healthcare_eda(data)

print("EDA completed successfully.")
print("EDA sections:")
print(list(healthcare_eda_results.keys()))

EDA completed successfully.
EDA sections:
['admissions', 'departments', 'doctors', 'patients', 'diagnoses', 'diagnosis_records', 'insurance_claims', 'payments', 'lab_tests', 'lab_results', 'medications', 'medication_records', 'procedures', 'procedure_records']

In [17]:
# ============================================================
# DISPLAY EDA RESULTS
# ============================================================

for table_name, results in healthcare_eda_results.items():

    print("\n" + "=" * 70)
    print(f" {table_name.upper()}")
    print("=" * 70)

    if isinstance(results, dict):

        for metric, value in results.items():
            print(f"{metric}: {value}")

    else:
        print(results)

======================================================================
 ADMISSIONS
======================================================================
total_admissions: 6500
unique_admissions: 6500
unique_patients: 2296
unique_doctors: 80
unique_departments: 12
admission_type_distribution: {'Emergency': 2747, 'Elective': 2480, 'Urgent': 1273}
discharge_status_distribution: {'Home': 4907, 'Transferred': 824, 'Rehab': 636, 'Expired': 133}
room_type_distribution: {'General': 2876, 'Semi-Private': 2014, 'Private': 1302, 'ICU': 288}
average_length_of_stay: 8.115692307692308
median_length_of_stay: 8.0
maximum_length_of_stay: 15
average_patient_satisfaction: 3.9802474864655846
median_patient_satisfaction: 4.0
readmission_distribution: {0: 5763, 1: 737}
readmission_rate: 11.338461538461539

======================================================================
 DEPARTMENTS
======================================================================
total_departments: 12
unique_departments: 12
department_distribution: {'Emergency': 1, 'Cardiology': 1, 'Oncology': 1, 'Neurology': 1, 'Orthopedics': 1, 'Pediatrics': 1, 'General Medicine': 1, 'ICU': 1, 'Radiology': 1, 'Surgery': 1, 'Obstetrics': 1, 'Dermatology': 1}

======================================================================
 DOCTORS
======================================================================
total_doctors: 80
unique_doctors: 80
doctors_by_department: {1: 5, 2: 5, 3: 9, 4: 6, 5: 5, 6: 7, 7: 7, 8: 9, 9: 9, 10: 7, 11: 4, 12: 7}

======================================================================
 PATIENTS
======================================================================
total_patients: 2500
unique_patients: 2500
duplicate_patient_rows: 0
gender_distribution: {'Male': 1231, 'Female': 1217, 'Other': 52}
insurance_distribution: {'Private': 1186, 'Medicare': 607, 'Medicaid': 584, 'Uninsured': 123}
smoking_distribution: {'Never': 1447, 'Former': 636, 'Current': 392, nan: 25}
blood_type_distribution: {'A+': 341, 'A-': 340, 'AB-': 318, 'B-': 317, 'O-': 302, 'O+': 300, 'B+': 296, 'AB+': 286}
state_distribution: {'MO': 2500}
city_distribution: {'Jefferson City': 271, 'Florissant': 268, 'St. Charles': 253, 'Columbia': 247, 'Independence': 247, 'St. Joseph': 245, 'Springfield': 242, 'St. Louis': 234, "O'Fallon": 230, 'Kansas City': 228, nan: 35}
valid_date_of_birth: 2500
invalid_date_of_birth: 0
missing_values: {'patient_id': 0, 'first_name': 0, 'last_name': 0, 'gender': 0, 'date_of_birth': 0, 'city': 35, 'state': 0, 'insurance_type': 0, 'smoking_status': 25, 'blood_type': 0, 'registration_date': 0}

======================================================================
 DIAGNOSES
======================================================================
total_diagnoses: 35
unique_diagnoses: 35
diagnosis_distribution: {'Hypertension': 1, 'Type 2 Diabetes': 1, 'Pneumonia': 1, 'Asthma': 1, 'Coronary Artery Disease': 1, 'Heart Failure': 1, 'COPD': 1, 'Migraine': 1, 'Osteoarthritis': 1, 'Fracture': 1, 'Depression': 1, 'Anxiety': 1, 'Stroke': 1, 'Chronic Kidney Disease': 1, 'Cancer': 1, 'Appendicitis': 1, 'Sepsis': 1, 'Influenza': 1, 'COVID-19': 1, 'Urinary Tract Infection': 1, 'Gastritis': 1, 'Anemia': 1, 'Hyperlipidemia': 1, 'Obesity': 1, 'Back Pain': 1, 'Dermatitis': 1, 'Thyroid Disorder': 1, 'Pregnancy Complication': 1, 'Gallstones': 1, 'Kidney Stones': 1, 'GERD': 1, 'Arthritis': 1, 'Lung Infection': 1, 'Arrhythmia': 1, 'Other': 1}

======================================================================
 DIAGNOSIS_RECORDS
======================================================================
total_records: 5250
unique_records: 5250
unique_admissions: 3607
diagnosis_distribution: {3017: 180, 3004: 168, 3020: 166, 3031: 164, 3023: 161, 3019: 161, 3001: 160, 3034: 159, 3026: 158, 3015: 158, 3027: 156, 3003: 155, 3014: 155, 3011: 155, 3021: 154, 3022: 154, 3033: 152, 3025: 150, 3006: 149, 3007: 149, 3029: 149, 3035: 147, 3012: 147, 3016: 146, 3002: 146, 3013: 145, 3024: 145, 3018: 141, 3032: 138, 3010: 134, 3005: 133, 3009: 132, 3030: 131, 3008: 127, 3028: 125}

======================================================================
 INSURANCE_CLAIMS
======================================================================
record_count: 6200
unique_claims: 6200
unique_patients: 2276
total_billed: 20005563.87
total_approved: 15175919.129999999
total_denied: 5860354.14
average_billed: 3226.7038500000003
average_approved: 2459.630329011345
average_denied: 945.2184096774193
median_billed: 2442.965
approval_rate: 75.85849231051941
denial_rate: 29.293621404933685
claim_status_distribution: {'Approved': 4248, 'Partially Approved': 1116, 'Denied': 460, 'Pending': 376}
missing_values: {'claim_id': 0, 'admission_id': 0, 'patient_id': 0, 'claim_date': 0, 'insurance_type': 0, 'billed_amount': 0, 'approved_amount': 30, 'denied_amount': 0, 'claim_status': 0}

======================================================================
 PAYMENTS
======================================================================
total_payments: 5800
unique_payments: 5800
unique_claims: 3771
unique_patients: 2247
payment_method_distribution: {'Insurance': 3574, 'Credit Card': 1149, 'Bank Transfer': 575, 'Cash': 502}
payment_status_distribution: {'Paid': 5137, 'Pending': 513, 'Refunded': 150}
total_payment_amount: 10662242.65
average_payment_amount: 1838.317698275862
median_payment_amount: 1319.58

======================================================================
 LAB_TESTS
======================================================================
total_lab_tests: 26
unique_lab_tests: 26
category_distribution: {'Vital Sign': 6, 'Chemistry': 5, 'Cardiac': 5, 'Hormone': 4, 'Other': 4, 'Blood': 2}

======================================================================
 LAB_RESULTS
======================================================================
total_lab_results: 18000
unique_lab_results: 18000
unique_admissions: 6103
unique_lab_tests: 26
abnormal_distribution: {'Normal': 12236, 'High': 2786, 'Low': 2447, 'Critical': 531}
average_result_value: 25.488013407821228
median_result_value: 20.005000000000003
result_unit_distribution: {'mmHg': 3135, 'mmol/L': 3012, 'g/dL': 2991, '%': 2985, 'mg/dL': 2947, 'U/L': 2930}

======================================================================
 MEDICATIONS
======================================================================
total_medications: 45
unique_medications: 45
medication_distribution: {'Metformin': 1, 'Lisinopril': 1, 'Atorvastatin': 1, 'Amlodipine': 1, 'Losartan': 1, 'Levothyroxine': 1, 'Albuterol': 1, 'Gabapentin': 1, 'Omeprazole': 1, 'Aspirin': 1, 'Insulin Glargine': 1, 'Amoxicillin': 1, 'Azithromycin': 1, 'Prednisone': 1, 'Furosemide': 1, 'Metoprolol': 1, 'Sertraline': 1, 'Ibuprofen': 1, 'Acetaminophen': 1, 'Warfarin': 1, 'Apixaban': 1, 'Clopidogrel': 1, 'Doxycycline': 1, 'Ciprofloxacin': 1, 'Pantoprazole': 1, 'Hydrochlorothiazide': 1, 'Rosuvastatin': 1, 'Montelukast': 1, 'Escitalopram': 1, 'Tramadol': 1, 'Ondansetron': 1, 'Morphine': 1, 'Heparin': 1, 'Vancomycin': 1, 'Ceftriaxone': 1, 'Sitagliptin': 1, 'Empagliflozin': 1, 'Insulin Lispro': 1, 'Meloxicam': 1, 'Fluoxetine': 1, 'Buspirone': 1, 'Prednisolone': 1, 'Famotidine': 1, 'Clindamycin': 1, 'Other': 1}

======================================================================
 MEDICATION_RECORDS
======================================================================
total_records: 11000
unique_records: 11000
unique_admissions: 5316
medication_distribution: {4038: 282, 4005: 280, 4016: 279, 4036: 273, 4009: 270, 4001: 270, 4028: 269, 4034: 263, 4030: 262, 4012: 262, 4024: 262, 4021: 261, 4003: 258, 4040: 255, 4037: 253, 4010: 250, 4027: 249, 4039: 249, 4044: 248, 4029: 248, 4017: 247, 4043: 245, 4011: 245, 4026: 242, 4019: 241, 4006: 241, 4018: 240, 4007: 238, 4015: 238, 4002: 236, 4031: 235, 4023: 235, 4014: 232, 4004: 231, 4020: 231, 4008: 231, 4041: 227, 4033: 227, 4025: 225, 4032: 215, 4022: 214, 4013: 213, 4035: 210, 4045: 210, 4042: 208}
frequency_distribution: {'Once Daily': 2817, 'As Needed': 2767, 'Twice Daily': 2719, 'Three Times Daily': 2697}
route_distribution: {'IM': 2246, 'IV': 2211, 'Oral': 2200, 'Subcutaneous': 2172, 'Topical': 2171}

======================================================================
 PROCEDURES
======================================================================
total_procedures: 40
unique_procedures: 40
procedure_distribution: {'Blood Test': 1, 'X-Ray': 1, 'CT Scan': 1, 'MRI': 1, 'Ultrasound': 1, 'ECG': 1, 'Echocardiogram': 1, 'Colonoscopy': 1, 'Endoscopy': 1, 'Appendectomy': 1, 'Hip Replacement': 1, 'Knee Replacement': 1, 'CABG': 1, 'Angioplasty': 1, 'Biopsy': 1, 'Chemotherapy': 1, 'Radiation Therapy': 1, 'Dialysis': 1, 'Physical Therapy': 1, 'Wound Care': 1, 'Vaccination': 1, 'C-Section': 1, 'Normal Delivery': 1, 'Laparoscopic Surgery': 1, 'Fracture Repair': 1, 'Cataract Surgery': 1, 'Dental Procedure': 1, 'Skin Procedure': 1, 'Pulmonary Function Test': 1, 'Other': 1, 'Procedure 0': 1, 'Procedure 1': 1, 'Procedure 2': 1, 'Procedure 3': 1, 'Procedure 4': 1, 'Procedure 5': 1, 'Procedure 6': 1, 'Procedure 7': 1, 'Procedure 8': 1, 'Procedure 9': 1}

======================================================================
 PROCEDURE_RECORDS
======================================================================
total_records: 8500
unique_records: 8500
unique_admissions: 4740
unique_procedures: 40
outcome_distribution: {'Successful': 7364, 'Complication': 798, 'Cancelled': 338}
total_actual_cost: 12333370.2
average_actual_cost: 1456.1239905548996
median_actual_cost: 1093.1399999999999

In [18]:
patients = data["patients"]

print("Total rows:", len(patients))
print("Unique patient IDs:", patients["patient_id"].nunique())
print("Duplicate patient IDs:",
      patients["patient_id"].duplicated().sum())

Total rows: 2500
Unique patient IDs: 2500
Duplicate patient IDs: 0

In [19]:
duplicate_patients = patients[
    patients["patient_id"].duplicated(keep=False)
].sort_values("patient_id")

display(duplicate_patients)

Empty DataFrame
Columns: [patient_id, first_name, last_name, gender, date_of_birth, city, state, insurance_type, smoking_status, blood_type, registration_date]
Index: []

In [20]:
claims = data["insurance_claims"]

claim_status_percentage = (
    claims["claim_status"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print(claim_status_percentage)

claim_status
Approved              68.52
Partially Approved    18.00
Denied                 7.42
Pending                6.06
Name: proportion, dtype: float64

In [21]:
diagnosis_records = data["diagnosis_records"]
diagnoses = data["diagnoses"]

diagnosis_analysis = diagnosis_records.merge(
    diagnoses,
    on="diagnosis_id",
    how="left"
)

diagnosis_counts = (
    diagnosis_analysis["diagnosis_name"]
    .value_counts()
)

print(diagnosis_counts.head(10))

diagnosis_name
Sepsis                     180
Asthma                     168
Urinary Tract Infection    166
GERD                       164
Hyperlipidemia             161
COVID-19                   161
Hypertension               160
Arrhythmia                 159
Dermatitis                 158
Cancer                     158
Name: count, dtype: int64

In [22]:
medication_records = data["medication_records"]
medications = data["medications"]

medication_analysis = medication_records.merge(
    medications,
    on="medication_id",
    how="left"
)

medication_counts = (
    medication_analysis["medication_name"]
    .value_counts()
)

print(medication_counts.head(10))

medication_name
Insulin Lispro    282
Losartan          280
Metoprolol        279
Sitagliptin       273
Omeprazole        270
Metformin         270
Montelukast       269
Vancomycin        263
Tramadol          262
Amoxicillin       262
Name: count, dtype: int64

In [23]:
procedure_records = data["procedure_records"]
procedures = data["procedures"]

procedure_analysis = procedure_records.merge(
    procedures,
    on="procedure_id",
    how="left"
)

procedure_counts = (
    procedure_analysis["procedure_name"]
    .value_counts()
)

print(procedure_counts.head(10))

procedure_name
Procedure 6                250
Pulmonary Function Test    241
Colonoscopy                237
Chemotherapy               236
Knee Replacement           233
Fracture Repair            228
Cataract Surgery           227
Angioplasty                227
Procedure 3                225
Echocardiogram             225
Name: count, dtype: int64

In [24]:
procedure_records = data["procedure_records"]

total = len(procedure_records)

complication_rate = (
    (procedure_records["outcome"] == "Complication").sum()
    / total * 100
)

cancellation_rate = (
    (procedure_records["outcome"] == "Cancelled").sum()
    / total * 100
)

success_rate = (
    (procedure_records["outcome"] == "Successful").sum()
    / total * 100
)

print(f"Success rate: {success_rate:.2f}%")
print(f"Complication rate: {complication_rate:.2f}%")
print(f"Cancellation rate: {cancellation_rate:.2f}%")

Success rate: 86.64%
Complication rate: 9.39%
Cancellation rate: 3.98%

In [25]:
# ============================================================
# VALIDATE EDA RESULTS
# ============================================================

print("=" * 70)
print("EDA VALIDATION")
print("=" * 70)

print("\nAdmissions:")
print("Expected: 6500")
print("Actual:", len(data["admissions"]))

print("\nPatients:")
print("Rows:", len(data["patients"]))
print("Unique Patient IDs:",
      data["patients"]["patient_id"].nunique())

print("\nInsurance Claims:")
print("Expected: 6200")
print("Actual:", len(data["insurance_claims"]))

print("\nPayments:")
print("Expected: 5800")
print("Actual:", len(data["payments"]))

print("\nLab Results:")
print("Expected: 18000")
print("Actual:", len(data["lab_results"]))

print("\nMedication Records:")
print("Expected: 11000")
print("Actual:", len(data["medication_records"]))

print("\nProcedure Records:")
print("Expected: 8500")
print("Actual:", len(data["procedure_records"]))

======================================================================
EDA VALIDATION
======================================================================

Admissions:
Expected: 6500
Actual: 6500

Patients:
Rows: 2500
Unique Patient IDs: 2500

Insurance Claims:
Expected: 6200
Actual: 6200

Payments:
Expected: 5800
Actual: 5800

Lab Results:
Expected: 18000
Actual: 18000

Medication Records:
Expected: 11000
Actual: 11000

Procedure Records:
Expected: 8500
Actual: 8500

In [26]:
# ============================================================
# CHECK INSURANCE CLAIMS
# ============================================================

print("Insurance Claims Type:")
print(type(data["insurance_claims"]))

print("\nInsurance Claims Shape:")
print(data["insurance_claims"].shape)

print("\nInsurance Claims Columns:")
print(data["insurance_claims"].columns.tolist())

print("\nFirst 5 Rows:")
display(data["insurance_claims"].head())

Insurance Claims Type:
<class 'pandas.DataFrame'>

Insurance Claims Shape:
(6200, 9)

Insurance Claims Columns:
['claim_id', 'admission_id', 'patient_id', 'claim_date', 'insurance_type', 'billed_amount', 'approved_amount', 'denied_amount', 'claim_status']

First 5 Rows:

,claim_id,admission_id,patient_id,claim_date,insurance_type,billed_amount,approved_amount,denied_amount,claim_status
0,1200001,704973,100550,2025-09-10,Private,3489.92,2527.91,3489.92,Denied
1,1200002,700340,101848,2021-07-03,Uninsured,783.71,437.20,346.51,Approved
2,1200003,701413,101385,2024-04-18,Medicaid,2087.27,1205.32,881.95,Partially Approved
3,1200004,701470,100271,2021-05-24,Medicare,8527.75,5662.09,2865.66,Partially Approved
4,1200005,700266,101840,2021-09-18,Medicaid,1126.83,828.96,297.87,Approved

In [27]:
# Admissions EDA
print("========== ADMISSIONS EDA ==========")
print(eda_results["admissions"])

# Patients EDA
print("\n========== PATIENTS EDA ==========")
print(eda_results["patients"])

# Insurance Claims EDA
print("\n========== INSURANCE CLAIMS EDA ==========")
print(eda_results["insurance_claims"])

# Payments EDA
print("\n========== PAYMENTS EDA ==========")
print(eda_results["payments"])

# Laboratory EDA
print("\n========== LAB RESULTS EDA ==========")
print(eda_results["lab_results"])

# Procedures EDA
print("\n========== PROCEDURES EDA ==========")
print(eda_results["procedure_records"])

========== ADMISSIONS EDA ==========
{'total_admissions': 6500, 'unique_admissions': 6500, 'unique_patients': 2296, 'unique_doctors': 80, 'unique_departments': 12, 'admission_type_distribution': {'Emergency': 2747, 'Elective': 2480, 'Urgent': 1273}, 'discharge_status_distribution': {'Home': 4907, 'Transferred': 824, 'Rehab': 636, 'Expired': 133}, 'room_type_distribution': {'General': 2876, 'Semi-Private': 2014, 'Private': 1302, 'ICU': 288}, 'average_length_of_stay': np.float64(8.115692307692308), 'median_length_of_stay': np.float64(8.0), 'maximum_length_of_stay': np.int64(15), 'average_patient_satisfaction': np.float64(3.9802474864655846), 'median_patient_satisfaction': np.float64(4.0), 'readmission_distribution': {0: 5763, 1: 737}, 'readmission_rate': np.float64(11.338461538461539)}

========== PATIENTS EDA ==========
{'total_patients': 2500, 'unique_patients': 2500, 'duplicate_patient_rows': 0, 'gender_distribution': {'Male': 1231, 'Female': 1217, 'Other': 52}, 'insurance_distribution': {'Private': 1186, 'Medicare': 607, 'Medicaid': 584, 'Uninsured': 123}, 'smoking_distribution': {'Never': 1447, 'Former': 636, 'Current': 392, nan: 25}, 'blood_type_distribution': {'A+': 341, 'A-': 340, 'AB-': 318, 'B-': 317, 'O-': 302, 'O+': 300, 'B+': 296, 'AB+': 286}, 'state_distribution': {'MO': 2500}, 'city_distribution': {'Jefferson City': 271, 'Florissant': 268, 'St. Charles': 253, 'Columbia': 247, 'Independence': 247, 'St. Joseph': 245, 'Springfield': 242, 'St. Louis': 234, "O'Fallon": 230, 'Kansas City': 228, nan: 35}, 'valid_date_of_birth': 2500, 'invalid_date_of_birth': 0, 'missing_values': {'patient_id': 0, 'first_name': 0, 'last_name': 0, 'gender': 0, 'date_of_birth': 0, 'city': 35, 'state': 0, 'insurance_type': 0, 'smoking_status': 25, 'blood_type': 0, 'registration_date': 0}}

========== INSURANCE CLAIMS EDA ==========
{'record_count': 6200, 'unique_claims': 6200, 'unique_patients': 2276, 'total_billed': np.float64(20005563.87), 'total_approved': np.float64(15175919.129999999), 'total_denied': np.float64(5860354.14), 'average_billed': np.float64(3226.7038500000003), 'average_approved': np.float64(2459.630329011345), 'average_denied': np.float64(945.2184096774193), 'median_billed': np.float64(2442.965), 'approval_rate': np.float64(75.85849231051941), 'denial_rate': np.float64(29.293621404933685), 'claim_status_distribution': {'Approved': 4248, 'Partially Approved': 1116, 'Denied': 460, 'Pending': 376}, 'missing_values': {'claim_id': 0, 'admission_id': 0, 'patient_id': 0, 'claim_date': 0, 'insurance_type': 0, 'billed_amount': 0, 'approved_amount': 30, 'denied_amount': 0, 'claim_status': 0}}

========== PAYMENTS EDA ==========
{'total_payments': 5800, 'unique_payments': 5800, 'unique_claims': 3771, 'unique_patients': 2247, 'payment_method_distribution': {'Insurance': 3574, 'Credit Card': 1149, 'Bank Transfer': 575, 'Cash': 502}, 'payment_status_distribution': {'Paid': 5137, 'Pending': 513, 'Refunded': 150}, 'total_payment_amount': np.float64(10662242.65), 'average_payment_amount': np.float64(1838.317698275862), 'median_payment_amount': np.float64(1319.58)}

========== LAB RESULTS EDA ==========
{'total_lab_results': 18000, 'unique_lab_results': 18000, 'unique_admissions': 6103, 'unique_lab_tests': 26, 'abnormal_distribution': {'Normal': 12236, 'High': 2786, 'Low': 2447, 'Critical': 531}, 'average_result_value': np.float64(25.488013407821228), 'median_result_value': np.float64(20.005000000000003), 'result_unit_distribution': {'mmHg': 3135, 'mmol/L': 3012, 'g/dL': 2991, '%': 2985, 'mg/dL': 2947, 'U/L': 2930}}

========== PROCEDURES EDA ==========
{'total_records': 8500, 'unique_records': 8500, 'unique_admissions': 4740, 'unique_procedures': 40, 'outcome_distribution': {'Successful': 7364, 'Complication': 798, 'Cancelled': 338}, 'total_actual_cost': np.float64(12333370.2), 'average_actual_cost': np.float64(1456.1239905548996), 'median_actual_cost': np.float64(1093.1399999999999)}

In [29]:
from pprint import pprint

pprint(eda_results)

{'admissions': {'admission_type_distribution': {'Elective': 2480,
                                                'Emergency': 2747,
                                                'Urgent': 1273},
                'average_length_of_stay': np.float64(8.115692307692308),
                'average_patient_satisfaction': np.float64(3.9802474864655846),
                'discharge_status_distribution': {'Expired': 133,
                                                  'Home': 4907,
                                                  'Rehab': 636,
                                                  'Transferred': 824},
                'maximum_length_of_stay': np.int64(15),
                'median_length_of_stay': np.float64(8.0),
                'median_patient_satisfaction': np.float64(4.0),
                'readmission_distribution': {0: 5763, 1: 737},
                'readmission_rate': np.float64(11.338461538461539),
                'room_type_distribution': {'General': 2876,
                                           'ICU': 288,
                                           'Private': 1302,
                                           'Semi-Private': 2014},
                'total_admissions': 6500,
                'unique_admissions': 6500,
                'unique_departments': 12,
                'unique_doctors': 80,
                'unique_patients': 2296},
 'departments': {'department_distribution': {'Cardiology': 1,
                                             'Dermatology': 1,
                                             'Emergency': 1,
                                             'General Medicine': 1,
                                             'ICU': 1,
                                             'Neurology': 1,
                                             'Obstetrics': 1,
                                             'Oncology': 1,
                                             'Orthopedics': 1,
                                             'Pediatrics': 1,
                                             'Radiology': 1,
                                             'Surgery': 1},
                 'total_departments': 12,
                 'unique_departments': 12},
 'diagnoses': {'diagnosis_distribution': {'Anemia': 1,
                                          'Anxiety': 1,
                                          'Appendicitis': 1,
                                          'Arrhythmia': 1,
                                          'Arthritis': 1,
                                          'Asthma': 1,
                                          'Back Pain': 1,
                                          'COPD': 1,
                                          'COVID-19': 1,
                                          'Cancer': 1,
                                          'Chronic Kidney Disease': 1,
                                          'Coronary Artery Disease': 1,
                                          'Depression': 1,
                                          'Dermatitis': 1,
                                          'Fracture': 1,
                                          'GERD': 1,
                                          'Gallstones': 1,
                                          'Gastritis': 1,
                                          'Heart Failure': 1,
                                          'Hyperlipidemia': 1,
                                          'Hypertension': 1,
                                          'Influenza': 1,
                                          'Kidney Stones': 1,
                                          'Lung Infection': 1,
                                          'Migraine': 1,
                                          'Obesity': 1,
                                          'Osteoarthritis': 1,
                                          'Other': 1,
                                          'Pneumonia': 1,
                                          'Pregnancy Complication': 1,
                                          'Sepsis': 1,
                                          'Stroke': 1,
                                          'Thyroid Disorder': 1,
                                          'Type 2 Diabetes': 1,
                                          'Urinary Tract Infection': 1},
               'total_diagnoses': 35,
               'unique_diagnoses': 35},
 'diagnosis_records': {'diagnosis_distribution': {3001: 160,
                                                  3002: 146,
                                                  3003: 155,
                                                  3004: 168,
                                                  3005: 133,
                                                  3006: 149,
                                                  3007: 149,
                                                  3008: 127,
                                                  3009: 132,
                                                  3010: 134,
                                                  3011: 155,
                                                  3012: 147,
                                                  3013: 145,
                                                  3014: 155,
                                                  3015: 158,
                                                  3016: 146,
                                                  3017: 180,
                                                  3018: 141,
                                                  3019: 161,
                                                  3020: 166,
                                                  3021: 154,
                                                  3022: 154,
                                                  3023: 161,
                                                  3024: 145,
                                                  3025: 150,
                                                  3026: 158,
                                                  3027: 156,
                                                  3028: 125,
                                                  3029: 149,
                                                  3030: 131,
                                                  3031: 164,
                                                  3032: 138,
                                                  3033: 152,
                                                  3034: 159,
                                                  3035: 147},
                       'total_records': 5250,
                       'unique_admissions': 3607,
                       'unique_records': 5250},
 'doctors': {'doctors_by_department': {1: 5,
                                       2: 5,
                                       3: 9,
                                       4: 6,
                                       5: 5,
                                       6: 7,
                                       7: 7,
                                       8: 9,
                                       9: 9,
                                       10: 7,
                                       11: 4,
                                       12: 7},
             'total_doctors': 80,
             'unique_doctors': 80},
 'insurance_claims': {'approval_rate': np.float64(75.85849231051941),
                      'average_approved': np.float64(2459.630329011345),
                      'average_billed': np.float64(3226.7038500000003),
                      'average_denied': np.float64(945.2184096774193),
                      'claim_status_distribution': {'Approved': 4248,
                                                    'Denied': 460,
                                                    'Partially Approved': 1116,
                                                    'Pending': 376},
                      'denial_rate': np.float64(29.293621404933685),
                      'median_billed': np.float64(2442.965),
                      'missing_values': {'admission_id': 0,
                                         'approved_amount': 30,
                                         'billed_amount': 0,
                                         'claim_date': 0,
                                         'claim_id': 0,
                                         'claim_status': 0,
                                         'denied_amount': 0,
                                         'insurance_type': 0,
                                         'patient_id': 0},
                      'record_count': 6200,
                      'total_approved': np.float64(15175919.129999999),
                      'total_billed': np.float64(20005563.87),
                      'total_denied': np.float64(5860354.14),
                      'unique_claims': 6200,
                      'unique_patients': 2276},
 'lab_results': {'abnormal_distribution': {'Critical': 531,
                                           'High': 2786,
                                           'Low': 2447,
                                           'Normal': 12236},
                 'average_result_value': np.float64(25.488013407821228),
                 'median_result_value': np.float64(20.005000000000003),
                 'result_unit_distribution': {'%': 2985,
                                              'U/L': 2930,
                                              'g/dL': 2991,
                                              'mg/dL': 2947,
                                              'mmHg': 3135,
                                              'mmol/L': 3012},
                 'total_lab_results': 18000,
                 'unique_admissions': 6103,
                 'unique_lab_results': 18000,
                 'unique_lab_tests': 26},
 'lab_tests': {'category_distribution': {'Blood': 2,
                                         'Cardiac': 5,
                                         'Chemistry': 5,
                                         'Hormone': 4,
                                         'Other': 4,
                                         'Vital Sign': 6},
               'total_lab_tests': 26,
               'unique_lab_tests': 26},
 'medication_records': {'frequency_distribution': {'As Needed': 2767,
                                                   'Once Daily': 2817,
                                                   'Three Times Daily': 2697,
                                                   'Twice Daily': 2719},
                        'medication_distribution': {4001: 270,
                                                    4002: 236,
                                                    4003: 258,
                                                    4004: 231,
                                                    4005: 280,
                                                    4006: 241,
                                                    4007: 238,
                                                    4008: 231,
                                                    4009: 270,
                                                    4010: 250,
                                                    4011: 245,
                                                    4012: 262,
                                                    4013: 213,
                                                    4014: 232,
                                                    4015: 238,
                                                    4016: 279,
                                                    4017: 247,
                                                    4018: 240,
                                                    4019: 241,
                                                    4020: 231,
                                                    4021: 261,
                                                    4022: 214,
                                                    4023: 235,
                                                    4024: 262,
                                                    4025: 225,
                                                    4026: 242,
                                                    4027: 249,
                                                    4028: 269,
                                                    4029: 248,
                                                    4030: 262,
                                                    4031: 235,
                                                    4032: 215,
                                                    4033: 227,
                                                    4034: 263,
                                                    4035: 210,
                                                    4036: 273,
                                                    4037: 253,
                                                    4038: 282,
                                                    4039: 249,
                                                    4040: 255,
                                                    4041: 227,
                                                    4042: 208,
                                                    4043: 245,
                                                    4044: 248,
                                                    4045: 210},
                        'route_distribution': {'IM': 2246,
                                               'IV': 2211,
                                               'Oral': 2200,
                                               'Subcutaneous': 2172,
                                               'Topical': 2171},
                        'total_records': 11000,
                        'unique_admissions': 5316,
                        'unique_records': 11000},
 'medications': {'medication_distribution': {'Acetaminophen': 1,
                                             'Albuterol': 1,
                                             'Amlodipine': 1,
                                             'Amoxicillin': 1,
                                             'Apixaban': 1,
                                             'Aspirin': 1,
                                             'Atorvastatin': 1,
                                             'Azithromycin': 1,
                                             'Buspirone': 1,
                                             'Ceftriaxone': 1,
                                             'Ciprofloxacin': 1,
                                             'Clindamycin': 1,
                                             'Clopidogrel': 1,
                                             'Doxycycline': 1,
                                             'Empagliflozin': 1,
                                             'Escitalopram': 1,
                                             'Famotidine': 1,
                                             'Fluoxetine': 1,
                                             'Furosemide': 1,
                                             'Gabapentin': 1,
                                             'Heparin': 1,
                                             'Hydrochlorothiazide': 1,
                                             'Ibuprofen': 1,
                                             'Insulin Glargine': 1,
                                             'Insulin Lispro': 1,
                                             'Levothyroxine': 1,
                                             'Lisinopril': 1,
                                             'Losartan': 1,
                                             'Meloxicam': 1,
                                             'Metformin': 1,
                                             'Metoprolol': 1,
                                             'Montelukast': 1,
                                             'Morphine': 1,
                                             'Omeprazole': 1,
                                             'Ondansetron': 1,
                                             'Other': 1,
                                             'Pantoprazole': 1,
                                             'Prednisolone': 1,
                                             'Prednisone': 1,
                                             'Rosuvastatin': 1,
                                             'Sertraline': 1,
                                             'Sitagliptin': 1,
                                             'Tramadol': 1,
                                             'Vancomycin': 1,
                                             'Warfarin': 1},
                 'total_medications': 45,
                 'unique_medications': 45},
 'patients': {'blood_type_distribution': {'A+': 341,
                                          'A-': 340,
                                          'AB+': 286,
                                          'AB-': 318,
                                          'B+': 296,
                                          'B-': 317,
                                          'O+': 300,
                                          'O-': 302},
              'city_distribution': {nan: 35,
                                    'Columbia': 247,
                                    'Florissant': 268,
                                    'Independence': 247,
                                    'Jefferson City': 271,
                                    'Kansas City': 228,
                                    "O'Fallon": 230,
                                    'Springfield': 242,
                                    'St. Charles': 253,
                                    'St. Joseph': 245,
                                    'St. Louis': 234},
              'duplicate_patient_rows': 0,
              'gender_distribution': {'Female': 1217,
                                      'Male': 1231,
                                      'Other': 52},
              'insurance_distribution': {'Medicaid': 584,
                                         'Medicare': 607,
                                         'Private': 1186,
                                         'Uninsured': 123},
              'invalid_date_of_birth': 0,
              'missing_values': {'blood_type': 0,
                                 'city': 35,
                                 'date_of_birth': 0,
                                 'first_name': 0,
                                 'gender': 0,
                                 'insurance_type': 0,
                                 'last_name': 0,
                                 'patient_id': 0,
                                 'registration_date': 0,
                                 'smoking_status': 25,
                                 'state': 0},
              'smoking_distribution': {nan: 25,
                                       'Current': 392,
                                       'Former': 636,
                                       'Never': 1447},
              'state_distribution': {'MO': 2500},
              'total_patients': 2500,
              'unique_patients': 2500,
              'valid_date_of_birth': 2500},
 'payments': {'average_payment_amount': np.float64(1838.317698275862),
              'median_payment_amount': np.float64(1319.58),
              'payment_method_distribution': {'Bank Transfer': 575,
                                              'Cash': 502,
                                              'Credit Card': 1149,
                                              'Insurance': 3574},
              'payment_status_distribution': {'Paid': 5137,
                                              'Pending': 513,
                                              'Refunded': 150},
              'total_payment_amount': np.float64(10662242.65),
              'total_payments': 5800,
              'unique_claims': 3771,
              'unique_patients': 2247,
              'unique_payments': 5800},
 'procedure_records': {'average_actual_cost': np.float64(1456.1239905548996),

In [ ]:
data["admissions"]

In [28]:
expected_sections = [
    "patients",
    "admissions",
    "departments",
    "doctors",
    "diagnoses",
    "diagnosis_records",
    "lab_tests",
    "lab_results",
    "medications",
    "medication_records",
    "procedures",
    "procedure_records",
    "insurance_claims",
    "payments"
]

for section in expected_sections:
    if section in eda_results:
        print(f"✓ {section}")
    else:
        print(f"✗ MISSING: {section}")

✓ patients
✓ admissions
✓ departments
✓ doctors
✓ diagnoses
✓ diagnosis_records
✓ lab_tests
✓ lab_results
✓ medications
✓ medication_records
✓ procedures
✓ procedure_records
✓ insurance_claims
✓ payments

In [30]:
print("Insurance claims EDA result:")
print(eda_results["insurance_claims"])

print("\nInsurance claims keys:")
print(eda_results["insurance_claims"].keys())

Insurance claims EDA result:
{'record_count': 6200, 'unique_claims': 6200, 'unique_patients': 2276, 'total_billed': np.float64(20005563.87), 'total_approved': np.float64(15175919.129999999), 'total_denied': np.float64(5860354.14), 'average_billed': np.float64(3226.7038500000003), 'average_approved': np.float64(2459.630329011345), 'average_denied': np.float64(945.2184096774193), 'median_billed': np.float64(2442.965), 'approval_rate': np.float64(75.85849231051941), 'denial_rate': np.float64(29.293621404933685), 'claim_status_distribution': {'Approved': 4248, 'Partially Approved': 1116, 'Denied': 460, 'Pending': 376}, 'missing_values': {'claim_id': 0, 'admission_id': 0, 'patient_id': 0, 'claim_date': 0, 'insurance_type': 0, 'billed_amount': 0, 'approved_amount': 30, 'denied_amount': 0, 'claim_status': 0}}

Insurance claims keys:
dict_keys(['record_count', 'unique_claims', 'unique_patients', 'total_billed', 'total_approved', 'total_denied', 'average_billed', 'average_approved', 'average_denied', 'median_billed', 'approval_rate', 'denial_rate', 'claim_status_distribution', 'missing_values'])

In [31]:
print("Insurance claims:", 
      eda_results["insurance_claims"]["record_count"],
      "| Actual:", len(data["insurance_claims"]))

Insurance claims: 6200 | Actual: 6200

In [32]:
# ============================================================
# EDA RESULT VALIDATION
# ============================================================

print("=" * 70)
print("EDA RESULT VALIDATION")
print("=" * 70)

print("Patients:",
      eda_results["patients"]["total_patients"],
      "| Actual:", len(data["patients"]))

print("Admissions:",
      eda_results["admissions"]["total_admissions"],
      "| Actual:", len(data["admissions"]))

print("Departments:",
      eda_results["departments"]["total_departments"],
      "| Actual:", len(data["departments"]))

print("Doctors:",
      eda_results["doctors"]["total_doctors"],
      "| Actual:", len(data["doctors"]))

print("Diagnoses:",
      eda_results["diagnoses"]["total_diagnoses"],
      "| Actual:", len(data["diagnoses"]))

print("Diagnosis records:",
      eda_results["diagnosis_records"]["total_records"],
      "| Actual:", len(data["diagnosis_records"]))

print("Lab tests:",
      eda_results["lab_tests"]["total_lab_tests"],
      "| Actual:", len(data["lab_tests"]))

print("Lab results:",
      eda_results["lab_results"]["total_lab_results"],
      "| Actual:", len(data["lab_results"]))

print("Medications:",
      eda_results["medications"]["total_medications"],
      "| Actual:", len(data["medications"]))

print("Medication records:",
      eda_results["medication_records"]["total_records"],
      "| Actual:", len(data["medication_records"]))

print("Procedures:",
      eda_results["procedures"]["total_procedures"],
      "| Actual:", len(data["procedures"]))

print("Procedure records:",
      eda_results["procedure_records"]["total_records"],
      "| Actual:", len(data["procedure_records"]))

# IMPORTANT: insurance_claims uses record_count
print("Insurance claims:",
      eda_results["insurance_claims"]["record_count"],
      "| Actual:", len(data["insurance_claims"]))

print("Payments:",
      eda_results["payments"]["total_payments"],
      "| Actual:", len(data["payments"]))

print("=" * 70)

======================================================================
EDA RESULT VALIDATION
======================================================================
Patients: 2500 | Actual: 2500
Admissions: 6500 | Actual: 6500
Departments: 12 | Actual: 12
Doctors: 80 | Actual: 80
Diagnoses: 35 | Actual: 35
Diagnosis records: 5250 | Actual: 5250
Lab tests: 26 | Actual: 26
Lab results: 18000 | Actual: 18000
Medications: 45 | Actual: 45
Medication records: 11000 | Actual: 11000
Procedures: 40 | Actual: 40
Procedure records: 8500 | Actual: 8500
Insurance claims: 6200 | Actual: 6200
Payments: 5800 | Actual: 5800
======================================================================

In [33]:
admissions = data["admissions"]

expected_avg_los = pd.to_numeric(
    admissions["length_of_stay"],
    errors="coerce"
).mean()

expected_avg_satisfaction = pd.to_numeric(
    admissions["patient_satisfaction"],
    errors="coerce"
).mean()

print("EDA average LOS:",
      eda_results["admissions"]["average_length_of_stay"])

print("Actual average LOS:",
      round(expected_avg_los, 2))

print()

print("EDA average satisfaction:",
      eda_results["admissions"]["average_patient_satisfaction"])

print("Actual average satisfaction:",
      round(expected_avg_satisfaction, 2))

EDA average LOS: 8.115692307692308
Actual average LOS: 8.12

EDA average satisfaction: 3.9802474864655846
Actual average satisfaction: 3.98

In [34]:
# ============================================================
# INSURANCE CLAIMS FINANCIAL VALIDATION
# ============================================================

claims = data["insurance_claims"]

# Convert financial columns to numeric
billed = pd.to_numeric(
    claims["billed_amount"],
    errors="coerce"
).sum()

approved = pd.to_numeric(
    claims["approved_amount"],
    errors="coerce"
).sum()

denied = pd.to_numeric(
    claims["denied_amount"],
    errors="coerce"
).sum()

# Calculate rates
approval_rate = (approved / billed) * 100
denial_rate = (denied / billed) * 100


# ============================================================
# COMPARE EDA RESULTS WITH ACTUAL CALCULATIONS
# ============================================================

print("=" * 70)
print("INSURANCE CLAIMS FINANCIAL VALIDATION")
print("=" * 70)

print("EDA billed:",
      eda_results["insurance_claims"]["total_billed"])

print("Actual billed:",
      round(billed, 2))

print()

print("EDA approved:",
      eda_results["insurance_claims"]["total_approved"])

print("Actual approved:",
      round(approved, 2))

print()

print("EDA denied:",
      eda_results["insurance_claims"]["total_denied"])

print("Actual denied:",
      round(denied, 2))

print()

print("EDA approval rate:",
      eda_results["insurance_claims"]["approval_rate"])

print("Actual approval rate:",
      round(approval_rate, 2))

print()

print("EDA denial rate:",
      eda_results["insurance_claims"]["denial_rate"])

print("Actual denial rate:",
      round(denial_rate, 2))

print("=" * 70)

======================================================================
INSURANCE CLAIMS FINANCIAL VALIDATION
======================================================================
EDA billed: 20005563.87
Actual billed: 20005563.87

EDA approved: 15175919.129999999
Actual approved: 15175919.13

EDA denied: 5860354.14
Actual denied: 5860354.14

EDA approval rate: 75.85849231051941
Actual approval rate: 75.86

EDA denial rate: 29.293621404933685
Actual denial rate: 29.29
======================================================================

In [35]:
# ============================================================
# CHECK APPROVED + DENIED AGAINST BILLED
# ============================================================

total_approved_denied = approved + denied

difference = total_approved_denied - billed

print("=" * 70)
print("APPROVED + DENIED VALIDATION")
print("=" * 70)

print("Total billed:           ", round(billed, 2))
print("Total approved:         ", round(approved, 2))
print("Total denied:           ", round(denied, 2))
print("Approved + denied:      ", round(total_approved_denied, 2))
print("Difference:             ", round(difference, 2))

print()

if abs(difference) < 0.01:
    print("STATUS: PASS")
    print("Approved + denied equals billed.")
else:
    print("STATUS: REVIEW")
    print("Approved + denied does NOT equal billed.")

print("=" * 70)

======================================================================
APPROVED + DENIED VALIDATION
======================================================================
Total billed:            20005563.87
Total approved:          15175919.13
Total denied:            5860354.14
Approved + denied:       21036273.27
Difference:              1030709.4

STATUS: REVIEW
Approved + denied does NOT equal billed.
======================================================================

In [36]:
procedures = data["procedure_records"]

actual_cost = pd.to_numeric(
    procedures["actual_cost"],
    errors="coerce"
)

print("EDA total cost:",
      eda_results["procedure_records"]["total_actual_cost"])

print("Actual total cost:",
      round(actual_cost.sum(), 2))

print()

print("EDA average cost:",
      eda_results["procedure_records"]["average_actual_cost"])

print("Actual average cost:",
      round(actual_cost.mean(), 2))

print()

print("EDA median cost:",
      eda_results["procedure_records"]["median_actual_cost"])

print("Actual median cost:",
      round(actual_cost.median(), 2))

EDA total cost: 12333370.2
Actual total cost: 12333370.2

EDA average cost: 1456.1239905548996
Actual average cost: 1456.12

EDA median cost: 1093.1399999999999
Actual median cost: 1093.14

In [39]:
# ============================================================
# CHECK INSURANCE CLAIMS EDA KEYS
# ============================================================

print("Insurance Claims EDA results:")
print(eda_results["insurance_claims"])

print("\nKeys:")
print(eda_results["insurance_claims"].keys())

Insurance Claims EDA results:
{'record_count': 6200, 'unique_claims': 6200, 'unique_patients': 2276, 'total_billed': np.float64(20005563.87), 'total_approved': np.float64(15175919.129999999), 'total_denied': np.float64(5860354.14), 'average_billed': np.float64(3226.7038500000003), 'average_approved': np.float64(2459.630329011345), 'average_denied': np.float64(945.2184096774193), 'median_billed': np.float64(2442.965), 'approval_rate': np.float64(75.85849231051941), 'denial_rate': np.float64(29.293621404933685), 'claim_status_distribution': {'Approved': 4248, 'Partially Approved': 1116, 'Denied': 460, 'Pending': 376}, 'missing_values': {'claim_id': 0, 'admission_id': 0, 'patient_id': 0, 'claim_date': 0, 'insurance_type': 0, 'billed_amount': 0, 'approved_amount': 30, 'denied_amount': 0, 'claim_status': 0}}

Keys:
dict_keys(['record_count', 'unique_claims', 'unique_patients', 'total_billed', 'total_approved', 'total_denied', 'average_billed', 'average_approved', 'average_denied', 'median_billed', 'approval_rate', 'denial_rate', 'claim_status_distribution', 'missing_values'])

In [41]:
for section, results in eda_results.items():
    print("=" * 70)
    print(section.upper())
    print("=" * 70)

    for key, value in results.items():
        print(f"{key}: {value}")

    print()

======================================================================
ADMISSIONS
======================================================================
total_admissions: 6500
unique_admissions: 6500
unique_patients: 2296
unique_doctors: 80
unique_departments: 12
admission_type_distribution: {'Emergency': 2747, 'Elective': 2480, 'Urgent': 1273}
discharge_status_distribution: {'Home': 4907, 'Transferred': 824, 'Rehab': 636, 'Expired': 133}
room_type_distribution: {'General': 2876, 'Semi-Private': 2014, 'Private': 1302, 'ICU': 288}
average_length_of_stay: 8.115692307692308
median_length_of_stay: 8.0
maximum_length_of_stay: 15
average_patient_satisfaction: 3.9802474864655846
median_patient_satisfaction: 4.0
readmission_distribution: {0: 5763, 1: 737}
readmission_rate: 11.338461538461539

======================================================================
DEPARTMENTS
======================================================================
total_departments: 12
unique_departments: 12
department_distribution: {'Emergency': 1, 'Cardiology': 1, 'Oncology': 1, 'Neurology': 1, 'Orthopedics': 1, 'Pediatrics': 1, 'General Medicine': 1, 'ICU': 1, 'Radiology': 1, 'Surgery': 1, 'Obstetrics': 1, 'Dermatology': 1}

======================================================================
DOCTORS
======================================================================
total_doctors: 80
unique_doctors: 80
doctors_by_department: {1: 5, 2: 5, 3: 9, 4: 6, 5: 5, 6: 7, 7: 7, 8: 9, 9: 9, 10: 7, 11: 4, 12: 7}

======================================================================
PATIENTS
======================================================================
total_patients: 2500
unique_patients: 2500
duplicate_patient_rows: 0
gender_distribution: {'Male': 1231, 'Female': 1217, 'Other': 52}
insurance_distribution: {'Private': 1186, 'Medicare': 607, 'Medicaid': 584, 'Uninsured': 123}
smoking_distribution: {'Never': 1447, 'Former': 636, 'Current': 392, nan: 25}
blood_type_distribution: {'A+': 341, 'A-': 340, 'AB-': 318, 'B-': 317, 'O-': 302, 'O+': 300, 'B+': 296, 'AB+': 286}
state_distribution: {'MO': 2500}
city_distribution: {'Jefferson City': 271, 'Florissant': 268, 'St. Charles': 253, 'Columbia': 247, 'Independence': 247, 'St. Joseph': 245, 'Springfield': 242, 'St. Louis': 234, "O'Fallon": 230, 'Kansas City': 228, nan: 35}
valid_date_of_birth: 2500
invalid_date_of_birth: 0
missing_values: {'patient_id': 0, 'first_name': 0, 'last_name': 0, 'gender': 0, 'date_of_birth': 0, 'city': 35, 'state': 0, 'insurance_type': 0, 'smoking_status': 25, 'blood_type': 0, 'registration_date': 0}

======================================================================
DIAGNOSES
======================================================================
total_diagnoses: 35
unique_diagnoses: 35
diagnosis_distribution: {'Hypertension': 1, 'Type 2 Diabetes': 1, 'Pneumonia': 1, 'Asthma': 1, 'Coronary Artery Disease': 1, 'Heart Failure': 1, 'COPD': 1, 'Migraine': 1, 'Osteoarthritis': 1, 'Fracture': 1, 'Depression': 1, 'Anxiety': 1, 'Stroke': 1, 'Chronic Kidney Disease': 1, 'Cancer': 1, 'Appendicitis': 1, 'Sepsis': 1, 'Influenza': 1, 'COVID-19': 1, 'Urinary Tract Infection': 1, 'Gastritis': 1, 'Anemia': 1, 'Hyperlipidemia': 1, 'Obesity': 1, 'Back Pain': 1, 'Dermatitis': 1, 'Thyroid Disorder': 1, 'Pregnancy Complication': 1, 'Gallstones': 1, 'Kidney Stones': 1, 'GERD': 1, 'Arthritis': 1, 'Lung Infection': 1, 'Arrhythmia': 1, 'Other': 1}

======================================================================
DIAGNOSIS_RECORDS
======================================================================
total_records: 5250
unique_records: 5250
unique_admissions: 3607
diagnosis_distribution: {3017: 180, 3004: 168, 3020: 166, 3031: 164, 3023: 161, 3019: 161, 3001: 160, 3034: 159, 3026: 158, 3015: 158, 3027: 156, 3003: 155, 3014: 155, 3011: 155, 3021: 154, 3022: 154, 3033: 152, 3025: 150, 3006: 149, 3007: 149, 3029: 149, 3035: 147, 3012: 147, 3016: 146, 3002: 146, 3013: 145, 3024: 145, 3018: 141, 3032: 138, 3010: 134, 3005: 133, 3009: 132, 3030: 131, 3008: 127, 3028: 125}

======================================================================
INSURANCE_CLAIMS
======================================================================
record_count: 6200
unique_claims: 6200
unique_patients: 2276
total_billed: 20005563.87
total_approved: 15175919.129999999
total_denied: 5860354.14
average_billed: 3226.7038500000003
average_approved: 2459.630329011345
average_denied: 945.2184096774193
median_billed: 2442.965
approval_rate: 75.85849231051941
denial_rate: 29.293621404933685
claim_status_distribution: {'Approved': 4248, 'Partially Approved': 1116, 'Denied': 460, 'Pending': 376}
missing_values: {'claim_id': 0, 'admission_id': 0, 'patient_id': 0, 'claim_date': 0, 'insurance_type': 0, 'billed_amount': 0, 'approved_amount': 30, 'denied_amount': 0, 'claim_status': 0}

======================================================================
PAYMENTS
======================================================================
total_payments: 5800
unique_payments: 5800
unique_claims: 3771
unique_patients: 2247
payment_method_distribution: {'Insurance': 3574, 'Credit Card': 1149, 'Bank Transfer': 575, 'Cash': 502}
payment_status_distribution: {'Paid': 5137, 'Pending': 513, 'Refunded': 150}
total_payment_amount: 10662242.65
average_payment_amount: 1838.317698275862
median_payment_amount: 1319.58

======================================================================
LAB_TESTS
======================================================================
total_lab_tests: 26
unique_lab_tests: 26
category_distribution: {'Vital Sign': 6, 'Chemistry': 5, 'Cardiac': 5, 'Hormone': 4, 'Other': 4, 'Blood': 2}

======================================================================
LAB_RESULTS
======================================================================
total_lab_results: 18000
unique_lab_results: 18000
unique_admissions: 6103
unique_lab_tests: 26
abnormal_distribution: {'Normal': 12236, 'High': 2786, 'Low': 2447, 'Critical': 531}
average_result_value: 25.488013407821228
median_result_value: 20.005000000000003
result_unit_distribution: {'mmHg': 3135, 'mmol/L': 3012, 'g/dL': 2991, '%': 2985, 'mg/dL': 2947, 'U/L': 2930}

======================================================================
MEDICATIONS
======================================================================
total_medications: 45
unique_medications: 45
medication_distribution: {'Metformin': 1, 'Lisinopril': 1, 'Atorvastatin': 1, 'Amlodipine': 1, 'Losartan': 1, 'Levothyroxine': 1, 'Albuterol': 1, 'Gabapentin': 1, 'Omeprazole': 1, 'Aspirin': 1, 'Insulin Glargine': 1, 'Amoxicillin': 1, 'Azithromycin': 1, 'Prednisone': 1, 'Furosemide': 1, 'Metoprolol': 1, 'Sertraline': 1, 'Ibuprofen': 1, 'Acetaminophen': 1, 'Warfarin': 1, 'Apixaban': 1, 'Clopidogrel': 1, 'Doxycycline': 1, 'Ciprofloxacin': 1, 'Pantoprazole': 1, 'Hydrochlorothiazide': 1, 'Rosuvastatin': 1, 'Montelukast': 1, 'Escitalopram': 1, 'Tramadol': 1, 'Ondansetron': 1, 'Morphine': 1, 'Heparin': 1, 'Vancomycin': 1, 'Ceftriaxone': 1, 'Sitagliptin': 1, 'Empagliflozin': 1, 'Insulin Lispro': 1, 'Meloxicam': 1, 'Fluoxetine': 1, 'Buspirone': 1, 'Prednisolone': 1, 'Famotidine': 1, 'Clindamycin': 1, 'Other': 1}

======================================================================
MEDICATION_RECORDS
======================================================================
total_records: 11000
unique_records: 11000
unique_admissions: 5316
medication_distribution: {4038: 282, 4005: 280, 4016: 279, 4036: 273, 4009: 270, 4001: 270, 4028: 269, 4034: 263, 4030: 262, 4012: 262, 4024: 262, 4021: 261, 4003: 258, 4040: 255, 4037: 253, 4010: 250, 4027: 249, 4039: 249, 4044: 248, 4029: 248, 4017: 247, 4043: 245, 4011: 245, 4026: 242, 4019: 241, 4006: 241, 4018: 240, 4007: 238, 4015: 238, 4002: 236, 4031: 235, 4023: 235, 4014: 232, 4004: 231, 4020: 231, 4008: 231, 4041: 227, 4033: 227, 4025: 225, 4032: 215, 4022: 214, 4013: 213, 4035: 210, 4045: 210, 4042: 208}
frequency_distribution: {'Once Daily': 2817, 'As Needed': 2767, 'Twice Daily': 2719, 'Three Times Daily': 2697}
route_distribution: {'IM': 2246, 'IV': 2211, 'Oral': 2200, 'Subcutaneous': 2172, 'Topical': 2171}

======================================================================
PROCEDURES
======================================================================
total_procedures: 40
unique_procedures: 40
procedure_distribution: {'Blood Test': 1, 'X-Ray': 1, 'CT Scan': 1, 'MRI': 1, 'Ultrasound': 1, 'ECG': 1, 'Echocardiogram': 1, 'Colonoscopy': 1, 'Endoscopy': 1, 'Appendectomy': 1, 'Hip Replacement': 1, 'Knee Replacement': 1, 'CABG': 1, 'Angioplasty': 1, 'Biopsy': 1, 'Chemotherapy': 1, 'Radiation Therapy': 1, 'Dialysis': 1, 'Physical Therapy': 1, 'Wound Care': 1, 'Vaccination': 1, 'C-Section': 1, 'Normal Delivery': 1, 'Laparoscopic Surgery': 1, 'Fracture Repair': 1, 'Cataract Surgery': 1, 'Dental Procedure': 1, 'Skin Procedure': 1, 'Pulmonary Function Test': 1, 'Other': 1, 'Procedure 0': 1, 'Procedure 1': 1, 'Procedure 2': 1, 'Procedure 3': 1, 'Procedure 4': 1, 'Procedure 5': 1, 'Procedure 6': 1, 'Procedure 7': 1, 'Procedure 8': 1, 'Procedure 9': 1}

======================================================================
PROCEDURE_RECORDS
======================================================================
total_records: 8500
unique_records: 8500
unique_admissions: 4740
unique_procedures: 40
outcome_distribution: {'Successful': 7364, 'Complication': 798, 'Cancelled': 338}
total_actual_cost: 12333370.2
average_actual_cost: 1456.1239905548996
median_actual_cost: 1093.1399999999999

In [42]:
# ============================================================
# HEALTHCARE EDA VALIDATION
# ============================================================

def validate_eda(data, eda_results):

    print("=" * 70)
    print("HEALTHCARE EDA VALIDATION")
    print("=" * 70)

    validation_results = {}

    # --------------------------------------------------------
    # EXPECTED SECTIONS
    # --------------------------------------------------------

    expected_sections = [
        "patients",
        "admissions",
        "departments",
        "doctors",
        "diagnoses",
        "diagnosis_records",
        "lab_tests",
        "lab_results",
        "medications",
        "medication_records",
        "procedures",
        "procedure_records",
        "insurance_claims",
        "payments"
    ]

    # --------------------------------------------------------
    # SECTION VALIDATION
    # --------------------------------------------------------

    print("\nSECTION VALIDATION")
    print("-" * 70)

    for section in expected_sections:

        if section in eda_results:
            print(f"✓ Section exists: {section}")
            validation_results[section] = {
                "section_exists": True
            }

        else:
            print(f"✗ Missing section: {section}")
            validation_results[section] = {
                "section_exists": False
            }

    # --------------------------------------------------------
    # RECORD COUNT VALIDATION
    # --------------------------------------------------------

    print("\n" + "-" * 70)
    print("RECORD COUNT VALIDATION")
    print("-" * 70)

    # The actual record-count key used by each EDA section.
    #
    # IMPORTANT:
    # We use only keys that are expected to represent
    # the number of rows/records in each table.
    # --------------------------------------------------------

    record_mapping = {
    "patients": "total_patients",
    "admissions": "total_admissions",
    "departments": "total_departments",
    "doctors": "total_doctors",
    "diagnoses": "total_diagnoses",
    "diagnosis_records": "total_records",
    "lab_tests": "total_lab_tests",
    "lab_results": "total_lab_results",
    "medications": "total_medications",
    "medication_records": "total_records",
    "procedures": "total_procedures",
    "procedure_records": "total_records",
    "insurance_claims": "record_count",
    "payments": "total_payments"
}

    for table, result_key in record_mapping.items():

        # Check that the table exists in data
        if table not in data:
            print(f"✗ {table}: table missing from data")
            continue

        # Check that the EDA section exists
        if table not in eda_results:
            print(f"✗ {table}: EDA section missing")
            continue

        # Check that the expected EDA metric exists
        if result_key not in eda_results[table]:

            print(
                f"⚠ {table}: EDA key '{result_key}' "
                f"not found"
            )

            print(
                "  Available keys:",
                list(eda_results[table].keys())
            )

            continue

        actual_count = len(data[table])
        eda_count = eda_results[table][result_key]

        if actual_count == eda_count:

            print(
                f"✓ {table}: "
                f"EDA={eda_count}, Actual={actual_count}"
            )

            validation_results[table]["record_count"] = {
                "eda": eda_count,
                "actual": actual_count,
                "match": True
            }

        else:

            print(
                f"✗ {table}: "
                f"EDA={eda_count}, Actual={actual_count}"
            )

            validation_results[table]["record_count"] = {
                "eda": eda_count,
                "actual": actual_count,
                "match": False
            }

    # --------------------------------------------------------
    # SUMMARY
    # --------------------------------------------------------

    print("\n" + "=" * 70)
    print("VALIDATION COMPLETE")
    print("=" * 70)

    return validation_results

In [43]:
validate_eda(data, eda_results)

======================================================================
HEALTHCARE EDA VALIDATION
======================================================================

SECTION VALIDATION
----------------------------------------------------------------------
✓ Section exists: patients
✓ Section exists: admissions
✓ Section exists: departments
✓ Section exists: doctors
✓ Section exists: diagnoses
✓ Section exists: diagnosis_records
✓ Section exists: lab_tests
✓ Section exists: lab_results
✓ Section exists: medications
✓ Section exists: medication_records
✓ Section exists: procedures
✓ Section exists: procedure_records
✓ Section exists: insurance_claims
✓ Section exists: payments

----------------------------------------------------------------------
RECORD COUNT VALIDATION
----------------------------------------------------------------------
✓ patients: EDA=2500, Actual=2500
✓ admissions: EDA=6500, Actual=6500
✓ departments: EDA=12, Actual=12
✓ doctors: EDA=80, Actual=80
✓ diagnoses: EDA=35, Actual=35
✓ diagnosis_records: EDA=5250, Actual=5250
✓ lab_tests: EDA=26, Actual=26
✓ lab_results: EDA=18000, Actual=18000
✓ medications: EDA=45, Actual=45
✓ medication_records: EDA=11000, Actual=11000
✓ procedures: EDA=40, Actual=40
✓ procedure_records: EDA=8500, Actual=8500
✓ insurance_claims: EDA=6200, Actual=6200
✓ payments: EDA=5800, Actual=5800

======================================================================
VALIDATION COMPLETE
======================================================================

{'patients': {'section_exists': True,
  'record_count': {'eda': 2500, 'actual': 2500, 'match': True}},
 'admissions': {'section_exists': True,
  'record_count': {'eda': 6500, 'actual': 6500, 'match': True}},
 'departments': {'section_exists': True,
  'record_count': {'eda': 12, 'actual': 12, 'match': True}},
 'doctors': {'section_exists': True,
  'record_count': {'eda': 80, 'actual': 80, 'match': True}},
 'diagnoses': {'section_exists': True,
  'record_count': {'eda': 35, 'actual': 35, 'match': True}},
 'diagnosis_records': {'section_exists': True,
  'record_count': {'eda': 5250, 'actual': 5250, 'match': True}},
 'lab_tests': {'section_exists': True,
  'record_count': {'eda': 26, 'actual': 26, 'match': True}},
 'lab_results': {'section_exists': True,
  'record_count': {'eda': 18000, 'actual': 18000, 'match': True}},
 'medications': {'section_exists': True,
  'record_count': {'eda': 45, 'actual': 45, 'match': True}},
 'medication_records': {'section_exists': True,
  'record_count': {'eda': 11000, 'actual': 11000, 'match': True}},
 'procedures': {'section_exists': True,
  'record_count': {'eda': 40, 'actual': 40, 'match': True}},
 'procedure_records': {'section_exists': True,
  'record_count': {'eda': 8500, 'actual': 8500, 'match': True}},
 'insurance_claims': {'section_exists': True,
  'record_count': {'eda': 6200, 'actual': 6200, 'match': True}},
 'payments': {'section_exists': True,
  'record_count': {'eda': 5800, 'actual': 5800, 'match': True}}}

In [44]:

# ============================================================
# FINAL EDA VALIDATION FUNCTION
# ============================================================

def validate_eda(data, eda_results):

    print("=" * 70)
    print("EDA VALIDATION")
    print("=" * 70)

    # --------------------------------------------------------
    # Expected EDA result keys and actual DataFrame tables
    # --------------------------------------------------------
    record_mapping = {
    "patients": "total_patients",
    "admissions": "total_admissions",
    "departments": "total_departments",
    "diagnoses": "total_diagnoses",
    "diagnosis_records": "total_records",
    "doctors": "total_doctors",
    "insurance_claims": "record_count",
    "lab_results": "total_lab_results",
    "lab_tests": "total_lab_tests",
    "medication_records": "total_records",
    "medications": "total_medications",
    "payments": "total_payments",
    "procedure_records": "total_records",
    "procedures": "total_procedures"
}

    validation_results = {}

    # --------------------------------------------------------
    # Validate record counts
    # --------------------------------------------------------
    for table, result_key in record_mapping.items():

        print("\n" + "-" * 70)
        print(table.upper())

        # Check that table exists in data
        if table not in data:
            print("❌ Table not found in data")
            validation_results[table] = False
            continue

        # Check that table exists in EDA results
        if table not in eda_results:
            print("❌ Table not found in EDA results")
            validation_results[table] = False
            continue

        # Check that expected EDA key exists
        if result_key not in eda_results[table]:
            print(f"❌ EDA key '{result_key}' not found")
            print("Available keys:")
            print(list(eda_results[table].keys()))
            validation_results[table] = False
            continue

        # Actual number of rows
        actual_count = len(data[table])

        # EDA value
        eda_count = eda_results[table][result_key]

        print("Expected / Actual DataFrame count:", actual_count)
        print("EDA count:", eda_count)

        # Compare
        if actual_count == eda_count:
            print("✅ PASS")
            validation_results[table] = True
        else:
            print("❌ FAIL")
            validation_results[table] = False

    # --------------------------------------------------------
    # Patient ID validation
    # --------------------------------------------------------
    print("\n" + "=" * 70)
    print("PATIENT ID VALIDATION")
    print("=" * 70)

    if "patients" in data and "patients" in eda_results:

        actual_unique_patients = data["patients"]["patient_id"].nunique()

        eda_unique_patients = eda_results["patients"].get(
            "unique_patients"
        )

        print("Actual unique patient IDs:", actual_unique_patients)
        print("EDA unique patient IDs:", eda_unique_patients)

        if actual_unique_patients == eda_unique_patients:
            print("✅ Unique patient IDs PASS")
        else:
            print("❌ Unique patient IDs FAIL")

    # --------------------------------------------------------
    # Summary
    # --------------------------------------------------------
    print("\n" + "=" * 70)
    print("FINAL VALIDATION SUMMARY")
    print("=" * 70)

    passed = sum(validation_results.values())
    total = len(validation_results)

    print(f"Passed: {passed}/{total}")
    print(f"Failed: {total - passed}/{total}")

    if passed == total:
        print("\n🎉 ALL EDA RECORD COUNT VALIDATIONS PASSED!")
    else:
        print("\n⚠️ SOME EDA VALIDATIONS FAILED.")
        print("Check the tables marked ❌ above.")

    return validation_results

In [45]:
validation_results = validate_eda(data, eda_results)

======================================================================
EDA VALIDATION
======================================================================

----------------------------------------------------------------------
PATIENTS
Expected / Actual DataFrame count: 2500
EDA count: 2500
✅ PASS

----------------------------------------------------------------------
ADMISSIONS
Expected / Actual DataFrame count: 6500
EDA count: 6500
✅ PASS

----------------------------------------------------------------------
DEPARTMENTS
Expected / Actual DataFrame count: 12
EDA count: 12
✅ PASS

----------------------------------------------------------------------
DIAGNOSES
Expected / Actual DataFrame count: 35
EDA count: 35
✅ PASS

----------------------------------------------------------------------
DIAGNOSIS_RECORDS
Expected / Actual DataFrame count: 5250
EDA count: 5250
✅ PASS

----------------------------------------------------------------------
DOCTORS
Expected / Actual DataFrame count: 80
EDA count: 80
✅ PASS

----------------------------------------------------------------------
INSURANCE_CLAIMS
Expected / Actual DataFrame count: 6200
EDA count: 6200
✅ PASS

----------------------------------------------------------------------
LAB_RESULTS
Expected / Actual DataFrame count: 18000
EDA count: 18000
✅ PASS

----------------------------------------------------------------------
LAB_TESTS
Expected / Actual DataFrame count: 26
EDA count: 26
✅ PASS

----------------------------------------------------------------------
MEDICATION_RECORDS
Expected / Actual DataFrame count: 11000
EDA count: 11000
✅ PASS

----------------------------------------------------------------------
MEDICATIONS
Expected / Actual DataFrame count: 45
EDA count: 45
✅ PASS

----------------------------------------------------------------------
PAYMENTS
Expected / Actual DataFrame count: 5800
EDA count: 5800
✅ PASS

----------------------------------------------------------------------
PROCEDURE_RECORDS
Expected / Actual DataFrame count: 8500
EDA count: 8500
✅ PASS

----------------------------------------------------------------------
PROCEDURES
Expected / Actual DataFrame count: 40
EDA count: 40
✅ PASS

======================================================================
PATIENT ID VALIDATION
======================================================================
Actual unique patient IDs: 2500
EDA unique patient IDs: 2500
✅ Unique patient IDs PASS

======================================================================
FINAL VALIDATION SUMMARY
======================================================================
Passed: 14/14
Failed: 0/14

🎉 ALL EDA RECORD COUNT VALIDATIONS PASSED!

In [46]:
# ============================================================
# HEALTHCARE EDA METRIC VALIDATION
# ============================================================

import pandas as pd
import numpy as np


def validate_eda_metrics(data, eda_results):

    print("=" * 70)
    print("EDA METRIC VALIDATION")
    print("=" * 70)

    validation_results = {}

    passed = 0
    failed = 0

    def check_metric(section, metric, actual, eda_value, tolerance=0.01):
        """
        Compare an independently calculated value with the EDA value.
        """

        nonlocal passed, failed

        # Convert numeric values safely
        try:
            actual_num = float(actual)
            eda_num = float(eda_value)

            match = np.isclose(
                actual_num,
                eda_num,
                atol=tolerance,
                rtol=1e-6
            )

        except (TypeError, ValueError):
            match = actual == eda_value

        if match:
            print(
                f"  {metric}: "
                f"EDA={eda_value}, Actual={actual} "
                f"✅ PASS"
            )
            passed += 1
        else:
            print(
                f"  {metric}: "
                f"EDA={eda_value}, Actual={actual} "
                f"❌ FAIL"
            )
            failed += 1

        validation_results.setdefault(section, {})[metric] = {
            "eda": eda_value,
            "actual": actual,
            "match": bool(match)
        }

    # ========================================================
    # PATIENTS
    # ========================================================

    print("\n" + "-" * 70)
    print("PATIENTS")
    print("-" * 70)

    patients = data["patients"]

    check_metric(
        "patients",
        "total_patients",
        len(patients),
        eda_results["patients"]["total_patients"]
    )

    check_metric(
        "patients",
        "unique_patients",
        patients["patient_id"].nunique(),
        eda_results["patients"]["unique_patients"]
    )

    check_metric(
        "patients",
        "duplicate_patient_rows",
        patients["patient_id"].duplicated().sum(),
        eda_results["patients"]["duplicate_patient_rows"]
    )

    # ========================================================
    # ADMISSIONS
    # ========================================================

    print("\n" + "-" * 70)
    print("ADMISSIONS")
    print("-" * 70)

    admissions = data["admissions"]

    check_metric(
        "admissions",
        "total_admissions",
        len(admissions),
        eda_results["admissions"]["total_admissions"]
    )

    check_metric(
        "admissions",
        "unique_admissions",
        admissions["admission_id"].nunique(),
        eda_results["admissions"]["unique_admissions"]
    )

    check_metric(
        "admissions",
        "unique_patients",
        admissions["patient_id"].nunique(),
        eda_results["admissions"]["unique_patients"]
    )

    check_metric(
        "admissions",
        "unique_doctors",
        admissions["doctor_id"].nunique(),
        eda_results["admissions"]["unique_doctors"]
    )

    check_metric(
        "admissions",
        "unique_departments",
        admissions["department_id"].nunique(),
        eda_results["admissions"]["unique_departments"]
    )

    # Length of stay
    los = pd.to_numeric(
        admissions["length_of_stay"],
        errors="coerce"
    )

    check_metric(
        "admissions",
        "average_length_of_stay",
        los.mean(),
        eda_results["admissions"]["average_length_of_stay"]
    )

    check_metric(
        "admissions",
        "median_length_of_stay",
        los.median(),
        eda_results["admissions"]["median_length_of_stay"]
    )

    check_metric(
        "admissions",
        "maximum_length_of_stay",
        los.max(),
        eda_results["admissions"]["maximum_length_of_stay"]
    )

    # Patient satisfaction
    satisfaction = pd.to_numeric(
        admissions["patient_satisfaction"],
        errors="coerce"
    )

    check_metric(
        "admissions",
        "average_patient_satisfaction",
        satisfaction.mean(),
        eda_results["admissions"]["average_patient_satisfaction"]
    )

    check_metric(
        "admissions",
        "median_patient_satisfaction",
        satisfaction.median(),
        eda_results["admissions"]["median_patient_satisfaction"]
    )

    # Readmission rate
    readmission = pd.to_numeric(
        admissions["readmission_30_days"],
        errors="coerce"
    )

    actual_readmission_rate = (
        readmission.mean() * 100
    )

    check_metric(
        "admissions",
        "readmission_rate",
        actual_readmission_rate,
        eda_results["admissions"]["readmission_rate"]
    )

    # ========================================================
    # DEPARTMENTS
    # ========================================================

    print("\n" + "-" * 70)
    print("DEPARTMENTS")
    print("-" * 70)

    departments = data["departments"]

    check_metric(
        "departments",
        "total_departments",
        len(departments),
        eda_results["departments"]["total_departments"]
    )

    check_metric(
        "departments",
        "unique_departments",
        departments["department_id"].nunique(),
        eda_results["departments"]["unique_departments"]
    )

    # ========================================================
    # DOCTORS
    # ========================================================

    print("\n" + "-" * 70)
    print("DOCTORS")
    print("-" * 70)

    doctors = data["doctors"]

    check_metric(
        "doctors",
        "total_doctors",
        len(doctors),
        eda_results["doctors"]["total_doctors"]
    )

    check_metric(
        "doctors",
        "unique_doctors",
        doctors["doctor_id"].nunique(),
        eda_results["doctors"]["unique_doctors"]
    )

    # ========================================================
    # DIAGNOSES
    # ========================================================

    print("\n" + "-" * 70)
    print("DIAGNOSES")
    print("-" * 70)

    diagnoses = data["diagnoses"]

    check_metric(
        "diagnoses",
        "total_diagnoses",
        len(diagnoses),
        eda_results["diagnoses"]["total_diagnoses"]
    )

    check_metric(
        "diagnoses",
        "unique_diagnoses",
        diagnoses["diagnosis_id"].nunique(),
        eda_results["diagnoses"]["unique_diagnoses"]
    )

    # ========================================================
    # DIAGNOSIS RECORDS
    # ========================================================

    print("\n" + "-" * 70)
    print("DIAGNOSIS RECORDS")
    print("-" * 70)

    diagnosis_records = data["diagnosis_records"]

    check_metric(
        "diagnosis_records",
        "total_records",
        len(diagnosis_records),
        eda_results["diagnosis_records"]["total_records"]
    )

    check_metric(
        "diagnosis_records",
        "unique_records",
        diagnosis_records["diagnosis_record_id"].nunique(),
        eda_results["diagnosis_records"]["unique_records"]
    )

    check_metric(
        "diagnosis_records",
        "unique_admissions",
        diagnosis_records["admission_id"].nunique(),
        eda_results["diagnosis_records"]["unique_admissions"]
    )

    # ========================================================
    # LAB TESTS
    # ========================================================

    print("\n" + "-" * 70)
    print("LAB TESTS")
    print("-" * 70)

    lab_tests = data["lab_tests"]

    check_metric(
        "lab_tests",
        "total_lab_tests",
        len(lab_tests),
        eda_results["lab_tests"]["total_lab_tests"]
    )

    check_metric(
        "lab_tests",
        "unique_lab_tests",
        lab_tests["lab_test_id"].nunique(),
        eda_results["lab_tests"]["unique_lab_tests"]
    )

    # ========================================================
    # LAB RESULTS
    # ========================================================

    print("\n" + "-" * 70)
    print("LAB RESULTS")
    print("-" * 70)

    lab_results = data["lab_results"]

    check_metric(
        "lab_results",
        "total_lab_results",
        len(lab_results),
        eda_results["lab_results"]["total_lab_results"]
    )

    check_metric(
        "lab_results",
        "unique_lab_results",
        lab_results["lab_result_id"].nunique(),
        eda_results["lab_results"]["unique_lab_results"]
    )

    check_metric(
        "lab_results",
        "unique_admissions",
        lab_results["admission_id"].nunique(),
        eda_results["lab_results"]["unique_admissions"]
    )

    check_metric(
        "lab_results",
        "unique_lab_tests",
        lab_results["lab_test_id"].nunique(),
        eda_results["lab_results"]["unique_lab_tests"]
    )

    result_value = pd.to_numeric(
        lab_results["result_value"],
        errors="coerce"
    )

    check_metric(
        "lab_results",
        "average_result_value",
        result_value.mean(),
        eda_results["lab_results"]["average_result_value"]
    )

    check_metric(
        "lab_results",
        "median_result_value",
        result_value.median(),
        eda_results["lab_results"]["median_result_value"]
    )

    # ========================================================
    # MEDICATIONS
    # ========================================================

    print("\n" + "-" * 70)
    print("MEDICATIONS")
    print("-" * 70)

    medications = data["medications"]

    check_metric(
        "medications",
        "total_medications",
        len(medications),
        eda_results["medications"]["total_medications"]
    )

    check_metric(
        "medications",
        "unique_medications",
        medications["medication_id"].nunique(),
        eda_results["medications"]["unique_medications"]
    )

    # ========================================================
    # MEDICATION RECORDS
    # ========================================================

    print("\n" + "-" * 70)
    print("MEDICATION RECORDS")
    print("-" * 70)

    medication_records = data["medication_records"]

    check_metric(
        "medication_records",
        "total_records",
        len(medication_records),
        eda_results["medication_records"]["total_records"]
    )

    check_metric(
        "medication_records",
        "unique_records",
        medication_records["medication_record_id"].nunique(),
        eda_results["medication_records"]["unique_records"]
    )

    check_metric(
        "medication_records",
        "unique_admissions",
        medication_records["admission_id"].nunique(),
        eda_results["medication_records"]["unique_admissions"]
    )

    # ========================================================
    # PROCEDURES
    # ========================================================

    print("\n" + "-" * 70)
    print("PROCEDURES")
    print("-" * 70)

    procedures = data["procedures"]

    check_metric(
        "procedures",
        "total_procedures",
        len(procedures),
        eda_results["procedures"]["total_procedures"]
    )

    check_metric(
        "procedures",
        "unique_procedures",
        procedures["procedure_id"].nunique(),
        eda_results["procedures"]["unique_procedures"]
    )

    # ========================================================
    # PROCEDURE RECORDS
    # ========================================================

    print("\n" + "-" * 70)
    print("PROCEDURE RECORDS")
    print("-" * 70)

    procedure_records = data["procedure_records"]

    check_metric(
        "procedure_records",
        "total_records",
        len(procedure_records),
        eda_results["procedure_records"]["total_records"]
    )

    check_metric(
        "procedure_records",
        "unique_records",
        procedure_records["procedure_record_id"].nunique(),
        eda_results["procedure_records"]["unique_records"]
    )

    check_metric(
        "procedure_records",
        "unique_admissions",
        procedure_records["admission_id"].nunique(),
        eda_results["procedure_records"]["unique_admissions"]
    )

    check_metric(
        "procedure_records",
        "unique_procedures",
        procedure_records["procedure_id"].nunique(),
        eda_results["procedure_records"]["unique_procedures"]
    )

    actual_total_cost = pd.to_numeric(
        procedure_records["actual_cost"],
        errors="coerce"
    ).sum()

    actual_average_cost = pd.to_numeric(
        procedure_records["actual_cost"],
        errors="coerce"
    ).mean()

    actual_median_cost = pd.to_numeric(
        procedure_records["actual_cost"],
        errors="coerce"
    ).median()

    check_metric(
        "procedure_records",
        "total_actual_cost",
        actual_total_cost,
        eda_results["procedure_records"]["total_actual_cost"]
    )

    check_metric(
        "procedure_records",
        "average_actual_cost",
        actual_average_cost,
        eda_results["procedure_records"]["average_actual_cost"]
    )

    check_metric(
        "procedure_records",
        "median_actual_cost",
        actual_median_cost,
        eda_results["procedure_records"]["median_actual_cost"]
    )

    # ========================================================
    # INSURANCE CLAIMS
    # ========================================================

    print("\n" + "-" * 70)
    print("INSURANCE CLAIMS")
    print("-" * 70)

    claims = data["insurance_claims"]

    check_metric(
        "insurance_claims",
        "record_count",
        len(claims),
        eda_results["insurance_claims"]["record_count"]
    )

    billed = pd.to_numeric(
        claims["billed_amount"],
        errors="coerce"
    )

    approved = pd.to_numeric(
        claims["approved_amount"],
        errors="coerce"
    )

    denied = pd.to_numeric(
        claims["denied_amount"],
        errors="coerce"
    )

    actual_total_billed = billed.sum()
    actual_total_approved = approved.sum()
    actual_total_denied = denied.sum()

    check_metric(
        "insurance_claims",
        "total_billed",
        actual_total_billed,
        eda_results["insurance_claims"]["total_billed"]
    )

    check_metric(
        "insurance_claims",
        "total_approved",
        actual_total_approved,
        eda_results["insurance_claims"]["total_approved"]
    )

    check_metric(
        "insurance_claims",
        "total_denied",
        actual_total_denied,
        eda_results["insurance_claims"]["total_denied"]
    )

    actual_approval_rate = (
        actual_total_approved / actual_total_billed
    ) * 100

    actual_denial_rate = (
        actual_total_denied / actual_total_billed
    ) * 100

    check_metric(
        "insurance_claims",
        "approval_rate",
        actual_approval_rate,
        eda_results["insurance_claims"]["approval_rate"]
    )

    check_metric(
        "insurance_claims",
        "denial_rate",
        actual_denial_rate,
        eda_results["insurance_claims"]["denial_rate"]
    )

    # ========================================================
    # PAYMENTS
    # ========================================================

    print("\n" + "-" * 70)
    print("PAYMENTS")
    print("-" * 70)

    payments = data["payments"]

    check_metric(
        "payments",
        "total_payments",
        len(payments),
        eda_results["payments"]["total_payments"]
    )

    check_metric(
        "payments",
        "unique_payments",
        payments["payment_id"].nunique(),
        eda_results["payments"]["unique_payments"]
    )

    check_metric(
        "payments",
        "unique_claims",
        payments["claim_id"].nunique(),
        eda_results["payments"]["unique_claims"]
    )

    check_metric(
        "payments",
        "unique_patients",
        payments["patient_id"].nunique(),
        eda_results["payments"]["unique_patients"]
    )

    payment_amount = pd.to_numeric(
        payments["payment_amount"],
        errors="coerce"
    )

    check_metric(
        "payments",
        "total_payment_amount",
        payment_amount.sum(),
        eda_results["payments"]["total_payment_amount"]
    )

    check_metric(
        "payments",
        "average_payment_amount",
        payment_amount.mean(),
        eda_results["payments"]["average_payment_amount"]
    )

    check_metric(
        "payments",
        "median_payment_amount",
        payment_amount.median(),
        eda_results["payments"]["median_payment_amount"]
    )

    # ========================================================
    # FINAL SUMMARY
    # ========================================================

    print("\n" + "=" * 70)
    print("FINAL METRIC VALIDATION SUMMARY")
    print("=" * 70)

    total = passed + failed

    print(f"Passed: {passed}/{total}")
    print(f"Failed: {failed}/{total}")

    if failed == 0:
        print("\n🎉 ALL EDA METRIC VALIDATIONS PASSED!")
    else:
        print("\n⚠️ SOME EDA METRIC VALIDATIONS FAILED.")
        print("Review the metrics marked ❌ above.")

    return validation_results

In [ ]:
metric_validation_results = validate_eda_metrics(
    data,
    eda_results
)

# Business Analysis and Performance Comparison

In [ ]:
# ============================================================
# CHECK BUSINESS ANALYSIS MODULE
# ============================================================

import business_analysis
import importlib

importlib.reload(business_analysis)

print("business_analysis module imported successfully!")


# ============================================================
# RUN ALL BUSINESS ANALYSIS
# ============================================================
business_results = business_analysis.run_business_analysis(data)
print("Business analysis completed successfully!")
# ============================================================
# CHECK BUSINESS ANALYSIS RESULTS
# ============================================================
print(business_results.keys())
# ============================================================
# BUSINESS SUMMARY
# ============================================================

business_results["business_summary"]
# ============================================================
# DEPARTMENT PERFORMANCE
# ============================================================
business_results["department_performance"]
# ============================================================
# ADMISSION TYPE COMPARISON
# ============================================================

business_results["admission_type_comparison"]
# ============================================================
# INSURANCE PERFORMANCE
# ============================================================
business_results["insurance_performance"]
# ============================================================
# PROCEDURE PERFORMANCE
# ============================================================
business_results["procedure_performance"].head(10)
# ============================================================
# PROCEDURE CATEGORY COMPARISON
# ============================================================
business_results["procedure_category_comparison"]
# ============================================================
# DOCTOR WORKLOAD
# ============================================================
business_results["doctor_workload"].head(10)

In [ ]:
for name, df in data.items():
    print(f"\n{name}")
    print(df.columns.tolist())

# Healthcare Statistics Module Testing

In [ ]:
# ============================================================
# HEALTHCARE STATISTICS MODULE
# ============================================================

import healthcare_statistics
import importlib

importlib.reload(healthcare_statistics)

print("healthcare_statistics module loaded successfully!")

# ============================================================
# TEST INDIVIDUAL STATISTICS FUNCTIONS
# ============================================================

admissions_results = healthcare_statistics.admissions_statistics(data)

patients_results = healthcare_statistics.patient_statistics(data)

insurance_results = healthcare_statistics.insurance_statistics(data)

payment_results = healthcare_statistics.payment_statistics(data)

laboratory_results = healthcare_statistics.laboratory_statistics(data)

procedure_results = healthcare_statistics.procedure_statistics(data)


print("Admissions statistics:", admissions_results)
print()
print("Patient statistics:", patients_results)
print()
print("Insurance statistics:", insurance_results)
print()
print("Payment statistics:", payment_results)
print()
print("Laboratory statistics:", laboratory_results)
print()
print("Procedure statistics:", procedure_results)

# ============================================================
# TEST COMPLETE STATISTICS FUNCTION
# ============================================================

statistics_results = healthcare_statistics.calculate_statistics(data)

print("Statistics calculation completed successfully!")

# ============================================================
# CHECK STATISTICS SECTIONS
# ============================================================

print(statistics_results.keys())

In [ ]:
patient_stats = statistics_results["patients"]

print("Total Patients:", patient_stats["total_patients"])
print("Average Age:", patient_stats["average_age"])
print("Median Age:", patient_stats["median_age"])
print("Minimum Age:", patient_stats["minimum_age"])
print("Maximum Age:", patient_stats["maximum_age"])
print("Invalid DOB:", patient_stats["invalid_date_of_birth"])

In [ ]:
print("\nGender Distribution:")
print(patient_stats["gender_distribution"])

print("\nInsurance Distribution:")
print(patient_stats["insurance_distribution"])

print("\nSmoking Status Distribution:")
print(patient_stats["smoking_status_distribution"])

print("\nBlood Type Distribution:")
print(patient_stats["blood_type_distribution"])

print("\nState Distribution:")
print(patient_stats["state_distribution"])

## 7. Healthcare Data Visualizations

The following visualizations are used to identify patterns in

**patient demographics**, **hospital admissions**, **insurance coverage,**
**smoking status**, **laboratory results**, and **financial activity**.

In [ ]:
import visualization
import importlib

importlib.reload(visualization)

print("Visualization module loaded successfully!")

visualization.plot_gender_distribution(data)

plt.show()

# PATIENT ANALYSIS VISUALIZATIONS

In [ ]:
import matplotlib.pyplot as plt

fig, axes = plt.subplots(
    2,
    3,
    figsize=(18, 10)
)

visualization.plot_gender_distribution(data,  ax=axes[0, 0])

visualization.plot_age_distribution(data, ax=axes[0, 1])

visualization.plot_insurance_distribution(data,  ax=axes[0, 2])

visualization.plot_smoking_status(data, ax=axes[1, 0])

visualization.plot_multiple_admissions(data,   ax=axes[1, 1])

axes[1, 2].axis("off")

# ------------------------------------------------------------
# Layout
# ------------------------------------------------------------

fig.suptitle("PATIENT ANALYSIS VISUALIZATIONS",  fontsize=18,  fontweight="bold")

plt.tight_layout()
plt.show()

# HOSPITAL OPERATIONS VISUALIZATIONS

In [ ]:
# ============================================================
# 2. HOSPITAL OPERATIONS VISUALIZATIONS - PARALLEL
# ============================================================

import matplotlib.pyplot as plt

# Create 2 rows × 2 columns
fig, axes = plt.subplots(2, 2, figsize=(18, 10))

# ------------------------------------------------------------
# 1. Monthly Admissions
# ------------------------------------------------------------

visualization.plot_monthly_admissions(data,    ax=axes[0, 0])

# ------------------------------------------------------------
# 2. Admissions by Department
# ------------------------------------------------------------

visualization.plot_admissions_by_department(data,    ax=axes[0, 1])

# ------------------------------------------------------------
# 3. Average Length of Stay by Department
# ------------------------------------------------------------

visualization.plot_average_los_by_department(data,    ax=axes[1, 0])

# ------------------------------------------------------------
# 4. Doctor Workload
# ------------------------------------------------------------

visualization.plot_doctor_workload(data,    ax=axes[1, 1])

# ------------------------------------------------------------
# Overall title
# ------------------------------------------------------------

fig.suptitle(
    "Hospital Operations Analysis",
    fontsize=18,
    fontweight="bold"
)

# Adjust spacing
plt.tight_layout(rect=[0, 0, 1, 0.96])

# Display
plt.show()

# CLINICAL SERVICES VISUALIZATIONS

In [ ]:

fig, axes = plt.subplots(2,  3,   figsize=(18, 10))

# ------------------------------------------------------------
# 1. Top Diagnoses
# ------------------------------------------------------------
visualization.plot_top_diagnoses(data,   ax=axes[0, 0])
# ------------------------------------------------------------
# 2. Top Lab Tests
# ------------------------------------------------------------

visualization.plot_top_lab_tests(data,   ax=axes[0, 1])

# ------------------------------------------------------------
# 3. Abnormal Lab Results
# ------------------------------------------------------------

visualization.plot_abnormal_lab_results(data,   ax=axes[0, 2])

# ------------------------------------------------------------
# 4. Top Medications
# ------------------------------------------------------------

visualization.plot_top_medications(data,    ax=axes[1, 0])

# ------------------------------------------------------------
# 5. Top Procedures
# ------------------------------------------------------------

visualization.plot_top_procedures(data,   ax=axes[1, 1])

# ------------------------------------------------------------
# Hide unused subplot
# ------------------------------------------------------------

axes[1, 2].axis("off")

# ------------------------------------------------------------
# Overall Title
# ------------------------------------------------------------

fig.suptitle("Clinical Services Analysis",   fontsize=18,    fontweight="bold")

# ------------------------------------------------------------
# Layout
# ------------------------------------------------------------

plt.tight_layout(rect=[0, 0, 1, 0.96])

plt.show()

# 4. INSURANCE AND FINANCIAL VISUALIZATIONS

In [ ]:
# ============================================================
# 4. INSURANCE AND FINANCIAL VISUALIZATIONS - PARALLEL
# ============================================================

import matplotlib.pyplot as plt

# Create 2 rows × 3 columns
fig, axes = plt.subplots(2, 3, figsize=(18, 10))

# ------------------------------------------------------------
# 1. Claim Status
# ------------------------------------------------------------

visualization.plot_claim_status(
    data,
    ax=axes[0, 0]
)

# ------------------------------------------------------------
# 2. Billed vs Approved Amount
# ------------------------------------------------------------

visualization.plot_billed_vs_approved(
    data,
    ax=axes[0, 1]
)

# ------------------------------------------------------------
# 3. Payment Distribution
# ------------------------------------------------------------

visualization.plot_payment_distribution(
    data,
    ax=axes[0, 2]
)

# ------------------------------------------------------------
# 4. Payment by Method
# ------------------------------------------------------------

visualization.plot_payment_by_method(
    data,
    ax=axes[1, 0]
)

# ------------------------------------------------------------
# 5. Financial Activity by Department
# ------------------------------------------------------------

visualization.plot_financial_activity_by_department(
    data,
    ax=axes[1, 1]
)

# ------------------------------------------------------------
# 6. Empty subplot
# ------------------------------------------------------------

axes[1, 2].axis("off")

# ------------------------------------------------------------
# Overall title
# ------------------------------------------------------------

fig.suptitle(
    "Insurance and Financial Analysis",
    fontsize=18,
    fontweight="bold"
)

# ------------------------------------------------------------
# Adjust spacing
# ------------------------------------------------------------

plt.tight_layout(rect=[0, 0, 1, 0.96])

# Display
plt.show()

# 5. INTEGRATED HEALTHCARE-FINANCIAL VISUALIZATIONS

In [274]:
# ============================================================
# 5. INTEGRATED HEALTHCARE-FINANCIAL VISUALIZATIONS - PARALLEL
# ============================================================

import matplotlib.pyplot as plt

# Create 2 rows × 3 columns
fig, axes = plt.subplots(2, 3, figsize=(18, 10))

# ------------------------------------------------------------
# 1. Length of Stay vs Paid Amount
# ------------------------------------------------------------

visualization.plot_los_vs_paid_amount(
    data,
    ax=axes[0, 0]
)

# ------------------------------------------------------------
# 2. Procedures vs Billed Amount
# ------------------------------------------------------------

visualization.plot_procedures_vs_billed_amount(
    data,
    ax=axes[0, 1]
)

# ------------------------------------------------------------
# 3. Utilization vs Length of Stay
# ------------------------------------------------------------

visualization.plot_utilization_vs_los(
    data,
    ax=axes[0, 2]
)

# ------------------------------------------------------------
# 4. Utilization vs Paid Amount
# ------------------------------------------------------------

visualization.plot_utilization_vs_paid_amount(
    data,
    ax=axes[1, 0]
)

# ------------------------------------------------------------
# 5. Utilization vs Billed Amount
# ------------------------------------------------------------

visualization.plot_utilization_vs_billed_amount(
    data,
    ax=axes[1, 1]
)

# ------------------------------------------------------------
# 6. Empty subplot
# ------------------------------------------------------------

axes[1, 2].axis("off")

# ------------------------------------------------------------
# Overall title
# ------------------------------------------------------------

fig.suptitle(
    "Integrated Healthcare-Financial Analysis",
    fontsize=18,
    fontweight="bold"
)

# ------------------------------------------------------------
# Adjust spacing
# ------------------------------------------------------------

plt.tight_layout(rect=[0, 0, 1, 0.96])

# ------------------------------------------------------------
# Display
# ------------------------------------------------------------

plt.show()

In [277]:
# ============================================================
# RELOAD VISUALIZATION MODULE
# ============================================================

import visualization
import importlib

importlib.reload(visualization)

print("Visualization module reloaded successfully!")

# ============================================================
# CORRELATION ANALYSIS
# ============================================================

visualization.plot_correlation_heatmap(data)

plt.show()

# Financial multivariate analysis

In [275]:
financial = data["insurance_claims"][
    [
        "billed_amount",
        "approved_amount",
        "denied_amount"
    ]
]

financial.corr()

In [276]:
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))

sns.heatmap(
    financial.corr(),
    annot=True,
    fmt=".2f"
)

plt.title("Financial Correlation Analysis")
plt.show()

In [ ]:
admissions["admission_date"] = pd.to_datetime(
    admissions["admission_date"]
)

admissions["admission_year"] = (
    admissions["admission_date"].dt.year
)

admissions["admission_month"] = (
    admissions["admission_date"].dt.month
)

admissions["admission_day"] = (
    admissions["admission_date"].dt.day
)

admissions["admission_day_of_week"] = (
    admissions["admission_date"].dt.day_name()
)

In [ ]:
# ============================================================
# STRONGEST CORRELATION RELATIONSHIPS
# ============================================================

strongest_correlations = (
    visualization.get_strongest_correlations(
        data,
        min_correlation=0.30
    )
)

strongest_correlations

In [ ]:
visualization.plot_correlation_with_regression(
    data["admissions"],
    "length_of_stay",
    "patient_satisfaction",
    title="Length of Stay vs Patient Satisfaction",
    xlabel="Length of Stay",
    ylabel="Patient Satisfaction"
)

       ●
                 ●
   ●       ●
          ───────── regression line
 ●
     ●
____________________________
 X variable

In [ ]:
visualization.plot_correlation_with_regression(
    data["insurance_claims"],
    "billed_amount",
    "approved_amount",
    title="Billed Amount vs Approved Amount",
    xlabel="Billed Amount ($)",
    ylabel="Approved Amount ($)"
)

In [ ]:
visualization.plot_correlation_with_regression(
    data["insurance_claims"],
    "billed_amount",
    "denied_amount",
    title="Billed Amount vs Denied Amount",
    xlabel="Billed Amount ($)",
    ylabel="Denied Amount ($)"
)

In [ ]:
procedure_admission = data["procedure_records"].merge(
    data["admissions"][["admission_id", "length_of_stay"]],
    on="admission_id",
    how="left"
)

visualization.plot_correlation_with_regression(
    procedure_admission,
    "length_of_stay",
    "actual_cost",
    title="Length of Stay vs Procedure Cost",
    xlabel="Length of Stay (Days)",
    ylabel="Procedure Cost ($)"
)

In [ ]:
# ============================================================
# CORRELATION ANALYSIS
# ============================================================

# 1. Billed Amount vs Approved Amount
visualization.plot_correlation_with_regression(
    data["insurance_claims"],
    "billed_amount",
    "approved_amount",
    title="Billed Amount vs Approved Amount",
    xlabel="Billed Amount ($)",
    ylabel="Approved Amount ($)"
)


# 2. Billed Amount vs Denied Amount
visualization.plot_correlation_with_regression(
    data["insurance_claims"],
    "billed_amount",
    "denied_amount",
    title="Billed Amount vs Denied Amount",
    xlabel="Billed Amount ($)",
    ylabel="Denied Amount ($)"
)


# 3. Length of Stay vs Patient Satisfaction
visualization.plot_correlation_with_regression(
    data["admissions"],
    "length_of_stay",
    "patient_satisfaction",
    title="Length of Stay vs Patient Satisfaction",
    xlabel="Length of Stay (Days)",
    ylabel="Patient Satisfaction"
)

In [ ]:
procedure_admission = data["procedure_records"].merge(
    data["admissions"][[
        "admission_id",
        "length_of_stay",
        "patient_satisfaction",
        "readmission_30_days"
    ]],
    on="admission_id",
    how="left"
)

visualization.plot_correlation_with_regression(
    procedure_admission,
    "length_of_stay",
    "actual_cost",
    title="Length of Stay vs Procedure Cost",
    xlabel="Length of Stay (Days)",
    ylabel="Actual Procedure Cost ($)"
)

In [ ]:
visualization.plot_correlation_with_regression(
    procedure_admission,
    "patient_satisfaction",
    "actual_cost",
    title="Patient Satisfaction vs Procedure Cost",
    xlabel="Patient Satisfaction",
    ylabel="Actual Procedure Cost ($)"
)

In [ ]:
procedure_financial = (
    data["procedure_records"]
    .merge(
        data["admissions"][["admission_id", "length_of_stay"]],
        on="admission_id",
        how="left"
    )
    .merge(
        data["insurance_claims"][
            ["admission_id", "billed_amount", "approved_amount", "denied_amount"]
        ],
        on="admission_id",
        how="left"
    )
)


visualization.plot_correlation_with_regression(
    procedure_financial,
    "actual_cost",
    "billed_amount",
    title="Procedure Cost vs Billed Amount",
    xlabel="Actual Procedure Cost ($)",
    ylabel="Billed Amount ($)"
)

In [ ]:
visualization.plot_correlation_with_regression(
    procedure_financial,
    "actual_cost",
    "approved_amount",
    title="Procedure Cost vs Approved Amount",
    xlabel="Actual Procedure Cost ($)",
    ylabel="Approved Amount ($)"
)

In [ ]:
# ============================================================
# CREATE POWER BI EXPORT FOLDER
# ============================================================

from pathlib import Path

BASE_DIR = Path.cwd()

POWERBI_DIR = BASE_DIR / "powerbi_data"

POWERBI_DIR.mkdir(exist_ok=True)

print("Power BI folder created:")
print(POWERBI_DIR)

print("\nFolder exists:", POWERBI_DIR.exists())

In [ ]:
# ============================================================
# EXPORT CLEAN DATA FOR POWER BI
# ============================================================

for table_name, df in data.items():

    output_file = POWERBI_DIR / f"{table_name}.csv"

    df.to_csv(
        output_file,
        index=False
    )

    print(f"Exported: {table_name}.csv")

In [ ]:
# ============================================================
# EXPORT CLEAN DATA FOR POWER BI
# ============================================================

for table_name, df in data.items():

    output_file = POWERBI_DIR / f"{table_name}.csv"

    df.to_csv(
        output_file,
        index=False
    )

    print(f"Exported: {table_name}.csv")

In [ ]:
output_file = POWERBI_DIR / f"{table_name}.csv"

POWERBI_DIR = BASE_DIR / "powerbi_data"

In [ ]:
# ============================================================
# VERIFY POWER BI EXPORT FILES
# ============================================================

exported_files = sorted(POWERBI_DIR.glob("*.csv"))

print("=" * 70)
print("POWER BI EXPORT VALIDATION")
print("=" * 70)

print("Number of exported files:", len(exported_files))
print()

for file in exported_files:
    print(file.name)

In [ ]:
# ============================================================
# CHECK EXPORTED DATA
# ============================================================

for file in exported_files:

    df = pd.read_csv(file)

    print(
        f"{file.name:30} "
        f"Rows: {len(df):6} | "
        f"Columns: {len(df.columns):3}"
    )

In [ ]:
# ============================================================
# CHECK ADMISSIONS COLUMNS
# ============================================================

print("Admissions columns:")
print()

for i, column in enumerate(data["admissions"].columns, start=1):
    print(f"{i:2}. {column}")

In [ ]:
# ============================================================
# CHECK ALL TABLE COLUMNS
# ============================================================

for table_name, df in data.items():

    print("=" * 70)
    print(table_name.upper())
    print("=" * 70)

    print("Rows:", len(df))
    print("Columns:", len(df.columns))

    print("\nColumns:")
    print(list(df.columns))
    print()

In [272]:
# ============================================================
# CLEAN POWER BI EXPORT
# ============================================================

POWERBI_TABLES = [
    "patients",
    "admissions",
    "departments",
    "diagnoses",
    "diagnosis_records",
    "doctors",
    "insurance_claims",
    "lab_results",
    "lab_tests",
    "medication_records",
    "medications",
    "payments",
    "procedure_records",
    "procedures"
]

for table_name in POWERBI_TABLES:

    df = data[table_name]

    output_file = POWERBI_DIR / f"{table_name}.csv"

    df.to_csv(
        output_file,
        index=False
    )

    print(
        f"{table_name:25} "
        f"Rows: {len(df):6} | "
        f"Columns: {len(df.columns):3}"
    )

print("\nClean Power BI export completed.")

In [273]:
# ============================================================
# FINAL POWER BI FILE CHECK
# ============================================================

for table_name in POWERBI_TABLES:

    file = POWERBI_DIR / f"{table_name}.csv"

    print(
        f"{table_name:25} "
        f"Exists: {file.exists()}"
    )

print("\nExpected Power BI tables:", len(POWERBI_TABLES))

In [ ]:
# ============================================================
# FINAL ANALYSIS
# ============================================================

from analysis import run_all_analysis

analysis_results = run_all_analysis(data)

print("Analysis completed successfully.")

print("\nAnalysis sections:")
for key in analysis_results:
    print("-", key)

In [ ]:
# ============================================================
# CHECK ADMISSIONS COLUMNS
# ============================================================

admissions = data["admissions"].copy()

print("Admissions shape:")
print(admissions.shape)

print("\nAdmissions columns:")
print(admissions.columns.tolist())

In [ ]:
admissions["admission_date"]

In [ ]:
import pandas as pd

admissions = data["admissions"].copy()

admissions["admission_date"] = pd.to_datetime(
    admissions["admission_date"],
    errors="coerce"
)

admissions["discharge_date"] = pd.to_datetime(
    admissions["discharge_date"],
    errors="coerce"
)

admissions["length_of_stay"] = (
    admissions["discharge_date"]
    - admissions["admission_date"]
).dt.days

admissions.loc[
    admissions["length_of_stay"] < 0,
    "length_of_stay"
] = pd.NA

data["admissions"] = admissions

## 8. Key Healthcare Insights

The visualizations were analyzed to identify important patterns
in patient demographics, hospital utilization, insurance coverage,
and financial activity.

The main areas examined were:

- Patient demographic characteristics
- Hospital admissions
- Insurance distribution
- Smoking status
- Payment behavior
- Laboratory results
- Relationship between numerical variables
- Admission patterns by gender and insurance type

### Patient Demographics

The patient population shows variation in age, gender,
insurance type, and smoking status. The age distribution
helps identify the major patient age groups served by the
healthcare organization.

## 9. Conclusion

This project demonstrates an end-to-end healthcare data analytics
workflow, including data loading, data cleaning, exploratory data
analysis, statistical analysis, and visualization.

The analysis provides insights into patient demographics,
hospital admissions, insurance coverage, laboratory results,
and financial activity.

The project can be extended into an interactive healthcare
dashboard using Power BI, allowing healthcare stakeholders to
explore these findings through filters, KPIs, and interactive
visualizations.

In [278]:
from pathlib import Path

current = Path.cwd()

print("Current folder:")
print(current)

print("\nDoes modules exist here?")
print((current / "modules").exists())

print("\nDoes data_loader.py exist?")
print((current / "modules" / "data_loader.py").exists())

In [ ]:
import os

print(os.listdir())

In [ ]:
data = load_all_data()

from pathlib import Path

# ============================================================
# EXPORT CLEANED DATA FOR POWER BI
# ============================================================

powerbi_folder = Path("powerbi_data")
powerbi_folder.mkdir(exist_ok=True)

for table_name, df in data.items():

    file_path = powerbi_folder / f"{table_name}_clean.csv"

    df.to_csv(
        file_path,
        index=False
    )

    print(f"Exported: {file_path}")